// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/ad_config.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// OS X Active Directory configuration.
type AdConfig struct {
	// The OS X-specific configuration name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	// Active Directory trust domain
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain"`
	// Canonical name of option
	Option string `protobuf:"bytes,3,opt,name=option,proto3" json:"option"`
	// Variable typed option value
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdConfig) Reset()         { *m = AdConfig{} }
func (m *AdConfig) String() string { return proto.CompactTextString(m) }
func (*AdConfig) ProtoMessage()    {}
func (*AdConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_430cf9df02ccca63, []int{0}
}

func (m *AdConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdConfig.Unmarshal(m, b)
}
func (m *AdConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdConfig.Marshal(b, m, deterministic)
}
func (m *AdConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdConfig.Merge(m, src)
}
func (m *AdConfig) XXX_Size() int {
	return xxx_messageInfo_AdConfig.Size(m)
}
func (m *AdConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AdConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AdConfig proto.InternalMessageInfo

func (m *AdConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AdConfig) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AdConfig) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

func (m *AdConfig) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*AdConfig)(nil), "schemas.AdConfig")
}

func init() { proto.RegisterFile("pb/ad_config.proto", fileDescriptor_430cf9df02ccca63) }

var fileDescriptor_430cf9df02ccca63 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0xce, 0xbf, 0x0e, 0x82, 0x30,
	0x10, 0xc7, 0xf1, 0xa0, 0x88, 0xda, 0xb1, 0x31, 0xa6, 0xa3, 0x71, 0x72, 0x91, 0x1a, 0x4d, 0x74,
	0x70, 0x52, 0xdf, 0xc0, 0xd1, 0xc5, 0xf4, 0x1f, 0xd0, 0x60, 0x7b, 0x15, 0xa8, 0x89, 0x6f, 0x6f,
	0x3c, 0xd8, 0xee, 0xfb, 0xb9, 0xe5, 0x47, 0x68, 0x90, 0x5c, 0xe8, 0xa7, 0x02, 0x5f, 0xd8, 0x32,
	0x0f, 0x0d, 0x74, 0x40, 0xa7, 0xad, 0xaa, 0x8c, 0x13, 0xed, 0x5a, 0x93, 0xd9, 0x45, 0xdf, 0xf0,
	0x45, 0x29, 0x49, 0xbd, 0x70, 0x86, 0x25, 0xab, 0x64, 0x33, 0xbf, 0xe3, 0x4d, 0x97, 0x24, 0xd3,
	0xe0, 0x84, 0xf5, 0x6c, 0x84, 0x3a, 0xd4, 0xdf, 0x21, 0x74, 0x16, 0x3c, 0x1b, 0xf7, 0xde, 0x17,
	0x5d, 0x90, 0xc9, 0x47, 0xbc, 0xa2, 0x61, 0x29, 0x72, 0x1f, 0xd7, 0xfd, 0x63, 0x57, 0xda, 0xae,
	0x8a, 0x32, 0x57, 0xe0, 0xb8, 0xb3, 0xaa, 0x36, 0xe1, 0x74, 0xe4, 0xd0, 0xbe, 0xa3, 0x69, 0xbe,
	0x5b, 0xdc, 0x24, 0x63, 0xc1, 0x43, 0x5d, 0x9e, 0x87, 0x65, 0x32, 0x43, 0x3d, 0xfc, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x27, 0xde, 0x17, 0x32, 0xbf, 0x00, 0x00, 0x00,
}
