// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/alf_explicit_auth.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ALF services explicitly allowed to perform networking.
type AlfExplicitAuth struct {
	// Process name explicitly allowed
	Process              string   `protobuf:"bytes,1,opt,name=process,proto3" json:"process"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlfExplicitAuth) Reset()         { *m = AlfExplicitAuth{} }
func (m *AlfExplicitAuth) String() string { return proto.CompactTextString(m) }
func (*AlfExplicitAuth) ProtoMessage()    {}
func (*AlfExplicitAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_de85e6a590b9dd90, []int{0}
}

func (m *AlfExplicitAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlfExplicitAuth.Unmarshal(m, b)
}
func (m *AlfExplicitAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlfExplicitAuth.Marshal(b, m, deterministic)
}
func (m *AlfExplicitAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlfExplicitAuth.Merge(m, src)
}
func (m *AlfExplicitAuth) XXX_Size() int {
	return xxx_messageInfo_AlfExplicitAuth.Size(m)
}
func (m *AlfExplicitAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_AlfExplicitAuth.DiscardUnknown(m)
}

var xxx_messageInfo_AlfExplicitAuth proto.InternalMessageInfo

func (m *AlfExplicitAuth) GetProcess() string {
	if m != nil {
		return m.Process
	}
	return ""
}

func init() {
	proto.RegisterType((*AlfExplicitAuth)(nil), "schemas.AlfExplicitAuth")
}

func init() { proto.RegisterFile("pb/alf_explicit_auth.proto", fileDescriptor_de85e6a590b9dd90) }

var fileDescriptor_de85e6a590b9dd90 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x48, 0xd2, 0x4f,
	0xcc, 0x49, 0x8b, 0x4f, 0xad, 0x28, 0xc8, 0xc9, 0x4c, 0xce, 0x2c, 0x89, 0x4f, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x2c, 0x56,
	0xd2, 0xe6, 0xe2, 0x77, 0xcc, 0x49, 0x73, 0x85, 0x2a, 0x71, 0x2c, 0x2d, 0xc9, 0x10, 0x92, 0xe0,
	0x62, 0x2f, 0x28, 0xca, 0x4f, 0x4e, 0x2d, 0x2e, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82,
	0x71, 0x9d, 0x8c, 0xa2, 0x0c, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5,
	0x73, 0x33, 0x93, 0xb3, 0x53, 0x0b, 0xcc, 0xcd, 0xf4, 0xf3, 0x8b, 0x0b, 0x4b, 0x53, 0x8b, 0x2a,
	0x75, 0xc1, 0x46, 0x27, 0x95, 0xa6, 0xe9, 0x17, 0x64, 0xa7, 0x5b, 0x43, 0x2d, 0x48, 0x62, 0x03,
	0x8b, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x42, 0x1e, 0xb3, 0x16, 0x8e, 0x00, 0x00, 0x00,
}
