// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/app.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// OS X applications installed in known search paths (e.g., /Applications).
type App struct {
	// Name of the Name.app folder
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	// Absolute and full Name.app path
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path"`
	// Info properties CFBundleName label
	BundleName string `protobuf:"bytes,3,opt,name=bundle_name,json=bundleName,proto3" json:"bundle_name"`
	// Info properties CFBundleVersion label
	BundleVersion string `protobuf:"bytes,4,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version"`
	// Application-set environment variables
	Environment string `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment"`
	// Does the app identify as a background agent
	Element string `protobuf:"bytes,6,opt,name=element,proto3" json:"element"`
	// Info properties DTCompiler label
	Compiler string `protobuf:"bytes,7,opt,name=compiler,proto3" json:"compiler"`
	// Info properties CFBundleDisplayName label
	DisplayName string `protobuf:"bytes,8,opt,name=display_name,json=displayName,proto3" json:"display_name"`
	// Info properties CFBundleGetInfoString label
	InfoString string `protobuf:"bytes,9,opt,name=info_string,json=infoString,proto3" json:"info_string"`
	// Info properties NSHumanReadableCopyright label
	Copyright string `protobuf:"bytes,10,opt,name=copyright,proto3" json:"copyright"`
	// The time that the app was last used
	LastOpenedTime       float64  `protobuf:"fixed64,11,opt,name=last_opened_time,json=lastOpenedTime,proto3" json:"last_opened_time"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_a05ecb5db23acf21, []int{0}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *App) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *App) GetBundleName() string {
	if m != nil {
		return m.BundleName
	}
	return ""
}

func (m *App) GetBundleVersion() string {
	if m != nil {
		return m.BundleVersion
	}
	return ""
}

func (m *App) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *App) GetElement() string {
	if m != nil {
		return m.Element
	}
	return ""
}

func (m *App) GetCompiler() string {
	if m != nil {
		return m.Compiler
	}
	return ""
}

func (m *App) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *App) GetInfoString() string {
	if m != nil {
		return m.InfoString
	}
	return ""
}

func (m *App) GetCopyright() string {
	if m != nil {
		return m.Copyright
	}
	return ""
}

func (m *App) GetLastOpenedTime() float64 {
	if m != nil {
		return m.LastOpenedTime
	}
	return 0
}

func init() {
	proto.RegisterType((*App)(nil), "schemas.App")
}

func init() { proto.RegisterFile("pb/app.proto", fileDescriptor_a05ecb5db23acf21) }

var fileDescriptor_a05ecb5db23acf21 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd1, 0xcb, 0x4a, 0xc3, 0x40,
	0x14, 0x06, 0x60, 0xd2, 0xd6, 0x5e, 0x4e, 0x6a, 0x91, 0x59, 0x0d, 0x22, 0xb4, 0x0a, 0x42, 0x37,
	0x36, 0xa2, 0xa0, 0x0b, 0x57, 0xfa, 0x00, 0x0a, 0x55, 0x5c, 0xb8, 0x09, 0x49, 0x7a, 0x9a, 0x0c,
	0xcd, 0x5c, 0x9c, 0x99, 0x14, 0xfa, 0xa8, 0xbe, 0x8d, 0xe4, 0x4c, 0xbc, 0xec, 0x66, 0xbe, 0xff,
	0x4f, 0x38, 0xc3, 0x81, 0xa9, 0xc9, 0x93, 0xcc, 0x98, 0x95, 0xb1, 0xda, 0x6b, 0x36, 0x72, 0x45,
	0x85, 0x32, 0x73, 0x17, 0x5f, 0x3d, 0xe8, 0x3f, 0x1a, 0xc3, 0x18, 0x0c, 0x54, 0x26, 0x91, 0x47,
	0x8b, 0x68, 0x39, 0x59, 0xd3, 0xb9, 0x35, 0x93, 0xf9, 0x8a, 0xf7, 0x82, 0xb5, 0x67, 0x36, 0x87,
	0x38, 0x6f, 0xd4, 0xa6, 0xc6, 0x94, 0xea, 0x7d, 0x8a, 0x20, 0xd0, 0x73, 0xfb, 0xd1, 0x25, 0xcc,
	0xba, 0xc2, 0x1e, 0xad, 0x13, 0x5a, 0xf1, 0x01, 0x75, 0x8e, 0x83, 0xbe, 0x07, 0x64, 0x0b, 0x88,
	0x51, 0xed, 0x85, 0xd5, 0x4a, 0xa2, 0xf2, 0xfc, 0x88, 0x3a, 0xff, 0x89, 0x71, 0x18, 0x61, 0x8d,
	0x94, 0x0e, 0x29, 0xfd, 0xb9, 0xb2, 0x53, 0x18, 0x17, 0x5a, 0x1a, 0x51, 0xa3, 0xe5, 0x23, 0x8a,
	0x7e, 0xef, 0xec, 0x1c, 0xa6, 0x1b, 0xe1, 0x4c, 0x9d, 0x1d, 0xc2, 0x80, 0xe3, 0xf0, 0xe3, 0xce,
	0x68, 0xc2, 0x39, 0xc4, 0x42, 0x6d, 0x75, 0xea, 0xbc, 0x15, 0xaa, 0xe4, 0x93, 0xf0, 0x84, 0x96,
	0x5e, 0x49, 0xd8, 0x19, 0x4c, 0x0a, 0x6d, 0x0e, 0x56, 0x94, 0x95, 0xe7, 0x40, 0xf1, 0x1f, 0xb0,
	0x25, 0x9c, 0xd4, 0x99, 0xf3, 0xa9, 0x36, 0xa8, 0x70, 0x93, 0x7a, 0x21, 0x91, 0xc7, 0x8b, 0x68,
	0x19, 0xad, 0x67, 0xad, 0xbf, 0x10, 0xbf, 0x09, 0x89, 0x4f, 0x37, 0x1f, 0xd7, 0xa5, 0xf0, 0x55,
	0x93, 0xaf, 0x0a, 0x2d, 0x13, 0x29, 0x8a, 0x1d, 0x9a, 0xfb, 0xbb, 0x44, 0xbb, 0xcf, 0x06, 0xed,
	0xe1, 0x8a, 0x36, 0x91, 0x37, 0xdb, 0xc4, 0xec, 0xca, 0x87, 0x6e, 0x1f, 0xf9, 0x90, 0xf4, 0xf6,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x66, 0x27, 0x0a, 0xaf, 0x01, 0x00, 0x00,
}
