// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/app_scheme.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// OS X application schemes and handlers (e.g., http, file, mailto).
type AppScheme struct {
	// Name of the scheme/protocol
	Scheme string `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme"`
	// Application label for the handler
	Handler string `protobuf:"bytes,2,opt,name=handler,proto3" json:"handler"`
	// 1 if this handler is the OS default
	Enabled              int32    `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppScheme) Reset()         { *m = AppScheme{} }
func (m *AppScheme) String() string { return proto.CompactTextString(m) }
func (*AppScheme) ProtoMessage()    {}
func (*AppScheme) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f1d6a14817e93f4, []int{0}
}

func (m *AppScheme) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppScheme.Unmarshal(m, b)
}
func (m *AppScheme) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppScheme.Marshal(b, m, deterministic)
}
func (m *AppScheme) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppScheme.Merge(m, src)
}
func (m *AppScheme) XXX_Size() int {
	return xxx_messageInfo_AppScheme.Size(m)
}
func (m *AppScheme) XXX_DiscardUnknown() {
	xxx_messageInfo_AppScheme.DiscardUnknown(m)
}

var xxx_messageInfo_AppScheme proto.InternalMessageInfo

func (m *AppScheme) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *AppScheme) GetHandler() string {
	if m != nil {
		return m.Handler
	}
	return ""
}

func (m *AppScheme) GetEnabled() int32 {
	if m != nil {
		return m.Enabled
	}
	return 0
}

func init() {
	proto.RegisterType((*AppScheme)(nil), "schemas.AppScheme")
}

func init() { proto.RegisterFile("pb/app_scheme.proto", fileDescriptor_3f1d6a14817e93f4) }

var fileDescriptor_3f1d6a14817e93f4 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x48, 0xd2, 0x4f,
	0x2c, 0x28, 0x88, 0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x07, 0xf3, 0x12, 0x8b, 0x95, 0xc2, 0xb9, 0x38, 0x1d, 0x0b, 0x0a, 0x82, 0xc1, 0x72, 0x42,
	0x62, 0x5c, 0x6c, 0x10, 0x55, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x9e, 0x90, 0x04,
	0x17, 0x7b, 0x46, 0x62, 0x5e, 0x4a, 0x4e, 0x6a, 0x91, 0x04, 0x13, 0x58, 0x02, 0xc6, 0x05, 0xc9,
	0xa4, 0xe6, 0x25, 0x26, 0xe5, 0xa4, 0xa6, 0x48, 0x30, 0x2b, 0x30, 0x6a, 0xb0, 0x06, 0xc1, 0xb8,
	0x4e, 0x46, 0x51, 0x06, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0xb9,
	0x99, 0xc9, 0xd9, 0xa9, 0x05, 0xe6, 0x66, 0xfa, 0xf9, 0xc5, 0x85, 0xa5, 0xa9, 0x45, 0x95, 0xba,
	0x60, 0x67, 0x24, 0x95, 0xa6, 0xe9, 0x17, 0x64, 0xa7, 0x5b, 0x43, 0x1d, 0x93, 0xc4, 0x06, 0x16,
	0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x5b, 0x8d, 0xc4, 0xb3, 0x00, 0x00, 0x00,
}
