// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/arp_cache.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Address resolution cache, both static and dynamic (from ARP, NDP).
type ArpCache struct {
	// IPv4 address target
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address"`
	// MAC address of broadcasted address
	Mac string `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac"`
	// Interface of the network for the MAC
	Interface string `protobuf:"bytes,3,opt,name=interface,proto3" json:"interface"`
	// 1 for true
	Permanent            string   `protobuf:"bytes,4,opt,name=permanent,proto3" json:"permanent"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArpCache) Reset()         { *m = ArpCache{} }
func (m *ArpCache) String() string { return proto.CompactTextString(m) }
func (*ArpCache) ProtoMessage()    {}
func (*ArpCache) Descriptor() ([]byte, []int) {
	return fileDescriptor_a53a0d191eca56f8, []int{0}
}

func (m *ArpCache) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArpCache.Unmarshal(m, b)
}
func (m *ArpCache) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArpCache.Marshal(b, m, deterministic)
}
func (m *ArpCache) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArpCache.Merge(m, src)
}
func (m *ArpCache) XXX_Size() int {
	return xxx_messageInfo_ArpCache.Size(m)
}
func (m *ArpCache) XXX_DiscardUnknown() {
	xxx_messageInfo_ArpCache.DiscardUnknown(m)
}

var xxx_messageInfo_ArpCache proto.InternalMessageInfo

func (m *ArpCache) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ArpCache) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *ArpCache) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

func (m *ArpCache) GetPermanent() string {
	if m != nil {
		return m.Permanent
	}
	return ""
}

func init() {
	proto.RegisterType((*ArpCache)(nil), "schemas.ArpCache")
}

func init() { proto.RegisterFile("pb/arp_cache.proto", fileDescriptor_a53a0d191eca56f8) }

var fileDescriptor_a53a0d191eca56f8 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xce, 0xbb, 0x8e, 0xc2, 0x30,
	0x10, 0x85, 0x61, 0x65, 0xb3, 0xda, 0x6c, 0x5c, 0x21, 0x57, 0x2e, 0x28, 0x10, 0x15, 0x0d, 0x31,
	0x02, 0x09, 0x0a, 0x2a, 0xe0, 0x0d, 0x28, 0x69, 0x90, 0xed, 0x4c, 0x2e, 0x8a, 0x1c, 0x0f, 0x63,
	0xa7, 0xe0, 0xed, 0x51, 0xcc, 0xad, 0x9b, 0xf9, 0xfe, 0xe6, 0x30, 0x8e, 0x5a, 0x2a, 0xc2, 0xab,
	0x51, 0xa6, 0x81, 0x02, 0xc9, 0x05, 0xc7, 0x33, 0x6f, 0x1a, 0xb0, 0xca, 0xcf, 0x89, 0xfd, 0x1f,
	0x08, 0x4f, 0x63, 0xe2, 0x82, 0x65, 0xaa, 0x2c, 0x09, 0xbc, 0x17, 0xc9, 0x2c, 0x59, 0xe4, 0xe7,
	0xf7, 0xcb, 0x27, 0x2c, 0xb5, 0xca, 0x88, 0x9f, 0xa8, 0xe3, 0xc9, 0xa7, 0x2c, 0x6f, 0xfb, 0x00,
	0x54, 0x29, 0x03, 0x22, 0x8d, 0xfe, 0x85, 0xb1, 0x22, 0x90, 0x55, 0x3d, 0xf4, 0x41, 0xfc, 0x3e,
	0xeb, 0x07, 0x8e, 0xeb, 0xcb, 0xaa, 0x6e, 0x43, 0x33, 0xe8, 0xc2, 0x38, 0x2b, 0x6d, 0x6b, 0x3a,
	0xc0, 0xdd, 0x56, 0x3a, 0x7f, 0x1b, 0x80, 0xee, 0xcb, 0xb8, 0x50, 0x0f, 0x95, 0xc4, 0xae, 0xde,
	0xbf, 0x76, 0xea, 0xbf, 0xa8, 0x9b, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x04, 0xf0, 0xbe, 0xdb,
	0xcd, 0x00, 0x00, 0x00,
}
