// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/atom_package.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Lists all atom packages in a directory or globally installed in a system.
type AtomPackage struct {
	// Package display name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	// Package supplied version
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version"`
	// Package supplied description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	// Package's package.json path
	Path string `protobuf:"bytes,4,opt,name=path,proto3" json:"path"`
	// License for package
	License string `protobuf:"bytes,5,opt,name=license,proto3" json:"license"`
	// Package supplied homepage
	Homepage             string   `protobuf:"bytes,6,opt,name=homepage,proto3" json:"homepage"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AtomPackage) Reset()         { *m = AtomPackage{} }
func (m *AtomPackage) String() string { return proto.CompactTextString(m) }
func (*AtomPackage) ProtoMessage()    {}
func (*AtomPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a87ad1048fd476f, []int{0}
}

func (m *AtomPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AtomPackage.Unmarshal(m, b)
}
func (m *AtomPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AtomPackage.Marshal(b, m, deterministic)
}
func (m *AtomPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AtomPackage.Merge(m, src)
}
func (m *AtomPackage) XXX_Size() int {
	return xxx_messageInfo_AtomPackage.Size(m)
}
func (m *AtomPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_AtomPackage.DiscardUnknown(m)
}

var xxx_messageInfo_AtomPackage proto.InternalMessageInfo

func (m *AtomPackage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AtomPackage) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AtomPackage) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AtomPackage) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *AtomPackage) GetLicense() string {
	if m != nil {
		return m.License
	}
	return ""
}

func (m *AtomPackage) GetHomepage() string {
	if m != nil {
		return m.Homepage
	}
	return ""
}

func init() {
	proto.RegisterType((*AtomPackage)(nil), "schemas.AtomPackage")
}

func init() { proto.RegisterFile("pb/atom_package.proto", fileDescriptor_7a87ad1048fd476f) }

var fileDescriptor_7a87ad1048fd476f = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xb1, 0x4a, 0xc6, 0x30,
	0x14, 0x85, 0xa9, 0xfe, 0xb6, 0x9a, 0x6e, 0x01, 0x21, 0x38, 0x15, 0x27, 0x17, 0x1b, 0x51, 0xd0,
	0xc1, 0x49, 0x9f, 0x40, 0x1c, 0x5d, 0x24, 0x89, 0xd7, 0x24, 0xd4, 0xf4, 0x5e, 0x93, 0x54, 0xf0,
	0x89, 0x7c, 0x4d, 0x49, 0x5a, 0xe5, 0xdf, 0xce, 0x39, 0x1f, 0x7c, 0x70, 0xd8, 0x29, 0x69, 0xa9,
	0x32, 0x86, 0x57, 0x52, 0x66, 0x52, 0x16, 0x46, 0x8a, 0x98, 0x91, 0x77, 0xc9, 0x38, 0x08, 0x2a,
	0x9d, 0xff, 0x34, 0xac, 0x7f, 0xc8, 0x18, 0x9e, 0x56, 0xcc, 0x39, 0xdb, 0xcd, 0x2a, 0x80, 0x68,
	0x86, 0xe6, 0xe2, 0xe4, 0xb9, 0x66, 0x2e, 0x58, 0xf7, 0x05, 0x31, 0x79, 0x9c, 0xc5, 0x41, 0x9d,
	0xff, 0x2a, 0x1f, 0x58, 0xff, 0x06, 0xc9, 0x44, 0x4f, 0xb9, 0xd0, 0xc3, 0x4a, 0xf7, 0xa7, 0xe2,
	0x23, 0x95, 0x9d, 0xd8, 0xad, 0xbe, 0x92, 0x8b, 0xef, 0xc3, 0x1b, 0x98, 0x13, 0x88, 0xa3, 0xd5,
	0xb7, 0x55, 0x7e, 0xc6, 0x8e, 0x1d, 0x06, 0x20, 0x65, 0x41, 0xb4, 0x15, 0xfd, 0xf7, 0xc7, 0xeb,
	0x97, 0x2b, 0xeb, 0xb3, 0x5b, 0xf4, 0x68, 0x30, 0xc8, 0xe0, 0xcd, 0x04, 0x74, 0x77, 0x2b, 0x31,
	0x7d, 0x2e, 0x10, 0xbf, 0x2f, 0xeb, 0x2f, 0xbd, 0xbc, 0x4b, 0x9a, 0xec, 0xfd, 0xf6, 0x4e, 0xb7,
	0x75, 0xbd, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x92, 0x57, 0x6e, 0x06, 0x01, 0x00, 0x00,
}
