// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/autoexec.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type Autoexec struct {
	// Path to the executable
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path"`
	// Name of the program
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	// Source table of the autoexec item
	Source               string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Autoexec) Reset()         { *m = Autoexec{} }
func (m *Autoexec) String() string { return proto.CompactTextString(m) }
func (*Autoexec) ProtoMessage()    {}
func (*Autoexec) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f3d056bc64b99ad, []int{0}
}

func (m *Autoexec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Autoexec.Unmarshal(m, b)
}
func (m *Autoexec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Autoexec.Marshal(b, m, deterministic)
}
func (m *Autoexec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Autoexec.Merge(m, src)
}
func (m *Autoexec) XXX_Size() int {
	return xxx_messageInfo_Autoexec.Size(m)
}
func (m *Autoexec) XXX_DiscardUnknown() {
	xxx_messageInfo_Autoexec.DiscardUnknown(m)
}

var xxx_messageInfo_Autoexec proto.InternalMessageInfo

func (m *Autoexec) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Autoexec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Autoexec) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func init() {
	proto.RegisterType((*Autoexec)(nil), "schemas.Autoexec")
}

func init() { proto.RegisterFile("pb/autoexec.proto", fileDescriptor_2f3d056bc64b99ad) }

var fileDescriptor_2f3d056bc64b99ad = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x48, 0xd2, 0x4f,
	0x2c, 0x2d, 0xc9, 0x4f, 0xad, 0x48, 0x4d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f,
	0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x2c, 0x56, 0xf2, 0xe2, 0xe2, 0x70, 0x84, 0x4a, 0x09, 0x09, 0x71,
	0xb1, 0x14, 0x24, 0x96, 0x64, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x20, 0xb1,
	0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0x88, 0x18, 0x88, 0x2d, 0x24, 0xc6, 0xc5, 0x56, 0x9c, 0x5f,
	0x5a, 0x94, 0x9c, 0x2a, 0xc1, 0x0c, 0x16, 0x85, 0xf2, 0x9c, 0x8c, 0xa2, 0x0c, 0xd2, 0x33, 0x4b,
	0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x73, 0x33, 0x93, 0xb3, 0x53, 0x0b, 0xcc, 0xcd,
	0xf4, 0xf3, 0x8b, 0x0b, 0x4b, 0x53, 0x8b, 0x2a, 0x75, 0xc1, 0x36, 0x27, 0x95, 0xa6, 0xe9, 0x17,
	0x64, 0xa7, 0x5b, 0x43, 0xed, 0x4f, 0x62, 0x03, 0x8b, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x0c, 0x76, 0x6a, 0x42, 0xa4, 0x00, 0x00, 0x00,
}
