// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/default_environment.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Default environment variables and values.
type DefaultEnvironment struct {
	// Name of the environment variable
	Variable string `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable"`
	// Value of the environment variable
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value"`
	// 1 if the variable needs expanding
	Expand               int32    `protobuf:"varint,3,opt,name=expand,proto3" json:"expand"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultEnvironment) Reset()         { *m = DefaultEnvironment{} }
func (m *DefaultEnvironment) String() string { return proto.CompactTextString(m) }
func (*DefaultEnvironment) ProtoMessage()    {}
func (*DefaultEnvironment) Descriptor() ([]byte, []int) {
	return fileDescriptor_33431182bf17c35f, []int{0}
}

func (m *DefaultEnvironment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultEnvironment.Unmarshal(m, b)
}
func (m *DefaultEnvironment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultEnvironment.Marshal(b, m, deterministic)
}
func (m *DefaultEnvironment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultEnvironment.Merge(m, src)
}
func (m *DefaultEnvironment) XXX_Size() int {
	return xxx_messageInfo_DefaultEnvironment.Size(m)
}
func (m *DefaultEnvironment) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultEnvironment.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultEnvironment proto.InternalMessageInfo

func (m *DefaultEnvironment) GetVariable() string {
	if m != nil {
		return m.Variable
	}
	return ""
}

func (m *DefaultEnvironment) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *DefaultEnvironment) GetExpand() int32 {
	if m != nil {
		return m.Expand
	}
	return 0
}

func init() {
	proto.RegisterType((*DefaultEnvironment)(nil), "schemas.DefaultEnvironment")
}

func init() { proto.RegisterFile("pb/default_environment.proto", fileDescriptor_33431182bf17c35f) }

var fileDescriptor_33431182bf17c35f = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x48, 0xd2, 0x4f,
	0x49, 0x4d, 0x4b, 0x2c, 0xcd, 0x29, 0x89, 0x4f, 0xcd, 0x2b, 0xcb, 0x2c, 0xca, 0xcf, 0xcb, 0x4d,
	0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d,
	0x2c, 0x56, 0x8a, 0xe3, 0x12, 0x72, 0x81, 0xa8, 0x72, 0x45, 0x28, 0x12, 0x92, 0xe2, 0xe2, 0x28,
	0x4b, 0x2c, 0xca, 0x4c, 0x4c, 0xca, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3,
	0x85, 0x44, 0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x98, 0xc0, 0x12, 0x10, 0x8e, 0x90,
	0x18, 0x17, 0x5b, 0x6a, 0x45, 0x41, 0x62, 0x5e, 0x8a, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x6b, 0x10,
	0x94, 0xe7, 0x64, 0x14, 0x65, 0x90, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab,
	0x9f, 0x9b, 0x99, 0x9c, 0x9d, 0x5a, 0x60, 0x6e, 0xa6, 0x9f, 0x5f, 0x5c, 0x58, 0x9a, 0x5a, 0x54,
	0xa9, 0x0b, 0x76, 0x4d, 0x52, 0x69, 0x9a, 0x7e, 0x41, 0x76, 0xba, 0x35, 0xd4, 0x4d, 0x49, 0x6c,
	0x60, 0x51, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xc8, 0x33, 0x58, 0xc3, 0x00, 0x00,
	0x00,
}
