// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/docker_image_label.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Docker image labels.
type DockerImageLabel struct {
	// Image ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	// Label key
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key"`
	// Optional label value
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DockerImageLabel) Reset()         { *m = DockerImageLabel{} }
func (m *DockerImageLabel) String() string { return proto.CompactTextString(m) }
func (*DockerImageLabel) ProtoMessage()    {}
func (*DockerImageLabel) Descriptor() ([]byte, []int) {
	return fileDescriptor_f36e44f07c13c7b2, []int{0}
}

func (m *DockerImageLabel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DockerImageLabel.Unmarshal(m, b)
}
func (m *DockerImageLabel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DockerImageLabel.Marshal(b, m, deterministic)
}
func (m *DockerImageLabel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DockerImageLabel.Merge(m, src)
}
func (m *DockerImageLabel) XXX_Size() int {
	return xxx_messageInfo_DockerImageLabel.Size(m)
}
func (m *DockerImageLabel) XXX_DiscardUnknown() {
	xxx_messageInfo_DockerImageLabel.DiscardUnknown(m)
}

var xxx_messageInfo_DockerImageLabel proto.InternalMessageInfo

func (m *DockerImageLabel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DockerImageLabel) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DockerImageLabel) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*DockerImageLabel)(nil), "schemas.DockerImageLabel")
}

func init() { proto.RegisterFile("pb/docker_image_label.proto", fileDescriptor_f36e44f07c13c7b2) }

var fileDescriptor_f36e44f07c13c7b2 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x48, 0xd2, 0x4f,
	0xc9, 0x4f, 0xce, 0x4e, 0x2d, 0x8a, 0xcf, 0xcc, 0x4d, 0x4c, 0x4f, 0x8d, 0xcf, 0x49, 0x4c, 0x4a,
	0xcd, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x2c,
	0x56, 0xf2, 0xe2, 0x12, 0x70, 0x01, 0x2b, 0xf2, 0x04, 0xa9, 0xf1, 0x01, 0x29, 0x11, 0xe2, 0xe3,
	0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe0,
	0x62, 0xce, 0x4e, 0xad, 0x94, 0x60, 0x02, 0x0b, 0x80, 0x98, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89,
	0x39, 0xa5, 0xa9, 0x12, 0xcc, 0x60, 0x31, 0x08, 0xc7, 0xc9, 0x28, 0xca, 0x20, 0x3d, 0xb3, 0x24,
	0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x3f, 0x37, 0x33, 0x39, 0x3b, 0xb5, 0xc0, 0xdc, 0x4c,
	0x3f, 0xbf, 0xb8, 0xb0, 0x34, 0xb5, 0xa8, 0x52, 0x17, 0x6c, 0x73, 0x52, 0x69, 0x9a, 0x7e, 0x41,
	0x76, 0xba, 0x35, 0xd4, 0xfe, 0x24, 0x36, 0xb0, 0xa8, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xc0,
	0xb6, 0xb6, 0x43, 0xae, 0x00, 0x00, 0x00,
}
