// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/docker_image.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Docker images information.
type DockerImage struct {
	// Image ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	// Time of creation as UNIX time
	Created int64 `protobuf:"varint,2,opt,name=created,proto3" json:"created"`
	// Size of image in bytes
	SizeBytes int64 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes"`
	// Comma-separated list of repository tags
	Tags                 string   `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DockerImage) Reset()         { *m = DockerImage{} }
func (m *DockerImage) String() string { return proto.CompactTextString(m) }
func (*DockerImage) ProtoMessage()    {}
func (*DockerImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc7756d812b505c0, []int{0}
}

func (m *DockerImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DockerImage.Unmarshal(m, b)
}
func (m *DockerImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DockerImage.Marshal(b, m, deterministic)
}
func (m *DockerImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DockerImage.Merge(m, src)
}
func (m *DockerImage) XXX_Size() int {
	return xxx_messageInfo_DockerImage.Size(m)
}
func (m *DockerImage) XXX_DiscardUnknown() {
	xxx_messageInfo_DockerImage.DiscardUnknown(m)
}

var xxx_messageInfo_DockerImage proto.InternalMessageInfo

func (m *DockerImage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DockerImage) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *DockerImage) GetSizeBytes() int64 {
	if m != nil {
		return m.SizeBytes
	}
	return 0
}

func (m *DockerImage) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func init() {
	proto.RegisterType((*DockerImage)(nil), "schemas.DockerImage")
}

func init() { proto.RegisterFile("pb/docker_image.proto", fileDescriptor_fc7756d812b505c0) }

var fileDescriptor_fc7756d812b505c0 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x48, 0xd2, 0x4f,
	0xc9, 0x4f, 0xce, 0x4e, 0x2d, 0x8a, 0xcf, 0xcc, 0x4d, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x2c, 0x56, 0xca, 0xe2, 0xe2, 0x76, 0x01,
	0x4b, 0x7b, 0x82, 0x64, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0x98, 0x32, 0x53, 0x84, 0x24, 0xb8, 0xd8, 0x93, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x53, 0x24,
	0x98, 0x14, 0x18, 0x35, 0x98, 0x83, 0x60, 0x5c, 0x21, 0x59, 0x2e, 0xae, 0xe2, 0xcc, 0xaa, 0xd4,
	0xf8, 0xa4, 0xca, 0x92, 0xd4, 0x62, 0x09, 0x66, 0xb0, 0x24, 0x27, 0x48, 0xc4, 0x09, 0x24, 0x20,
	0x24, 0xc4, 0xc5, 0x52, 0x92, 0x98, 0x5e, 0x2c, 0xc1, 0x02, 0x36, 0x0a, 0xcc, 0x76, 0x32, 0x8a,
	0x32, 0x48, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xcd, 0x4c, 0xce,
	0x4e, 0x2d, 0x30, 0x37, 0xd3, 0xcf, 0x2f, 0x2e, 0x2c, 0x4d, 0x2d, 0xaa, 0xd4, 0x05, 0xbb, 0x2c,
	0xa9, 0x34, 0x4d, 0xbf, 0x20, 0x3b, 0xdd, 0x1a, 0xea, 0xbe, 0x24, 0x36, 0xb0, 0xa8, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x27, 0x77, 0x47, 0x09, 0xc8, 0x00, 0x00, 0x00,
}
