// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/ec2_instance_tag.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// EC2 instance tag key value pairs.
type Ec2InstanceTag struct {
	// EC2 instance ID
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id"`
	// Tag key
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key"`
	// Tag value
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ec2InstanceTag) Reset()         { *m = Ec2InstanceTag{} }
func (m *Ec2InstanceTag) String() string { return proto.CompactTextString(m) }
func (*Ec2InstanceTag) ProtoMessage()    {}
func (*Ec2InstanceTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ffe19e4f3fef99a, []int{0}
}

func (m *Ec2InstanceTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ec2InstanceTag.Unmarshal(m, b)
}
func (m *Ec2InstanceTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ec2InstanceTag.Marshal(b, m, deterministic)
}
func (m *Ec2InstanceTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ec2InstanceTag.Merge(m, src)
}
func (m *Ec2InstanceTag) XXX_Size() int {
	return xxx_messageInfo_Ec2InstanceTag.Size(m)
}
func (m *Ec2InstanceTag) XXX_DiscardUnknown() {
	xxx_messageInfo_Ec2InstanceTag.DiscardUnknown(m)
}

var xxx_messageInfo_Ec2InstanceTag proto.InternalMessageInfo

func (m *Ec2InstanceTag) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *Ec2InstanceTag) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Ec2InstanceTag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Ec2InstanceTag)(nil), "schemas.Ec2InstanceTag")
}

func init() { proto.RegisterFile("pb/ec2_instance_tag.proto", fileDescriptor_7ffe19e4f3fef99a) }

var fileDescriptor_7ffe19e4f3fef99a = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x48, 0xd2, 0x4f,
	0x4d, 0x36, 0x8a, 0xcf, 0xcc, 0x2b, 0x2e, 0x49, 0xcc, 0x4b, 0x4e, 0x8d, 0x2f, 0x49, 0x4c, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x2c, 0x56, 0x8a,
	0xe4, 0xe2, 0x73, 0x4d, 0x36, 0xf2, 0x84, 0xaa, 0x08, 0x49, 0x4c, 0x17, 0x92, 0xe7, 0xe2, 0x86,
	0x6b, 0xc8, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x82, 0x09, 0x79, 0xa6, 0x08,
	0x09, 0x70, 0x31, 0x67, 0xa7, 0x56, 0x4a, 0x30, 0x81, 0x25, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6,
	0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x66, 0xb0, 0x18, 0x84, 0xe3, 0x64, 0x14, 0x65, 0x90, 0x9e,
	0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x9b, 0x99, 0x9c, 0x9d, 0x5a, 0x60,
	0x6e, 0xa6, 0x9f, 0x5f, 0x5c, 0x58, 0x9a, 0x5a, 0x54, 0xa9, 0x0b, 0x76, 0x48, 0x52, 0x69, 0x9a,
	0x7e, 0x41, 0x76, 0xba, 0x35, 0xd4, 0x39, 0x49, 0x6c, 0x60, 0x51, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x0c, 0xe7, 0x4e, 0xeb, 0xbb, 0x00, 0x00, 0x00,
}
