// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/etc_host.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Line-parsed /etc/hosts.
type EtcHost struct {
	// IP address mapping
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address"`
	// Raw hosts mapping
	Hostnames            string   `protobuf:"bytes,2,opt,name=hostnames,proto3" json:"hostnames"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EtcHost) Reset()         { *m = EtcHost{} }
func (m *EtcHost) String() string { return proto.CompactTextString(m) }
func (*EtcHost) ProtoMessage()    {}
func (*EtcHost) Descriptor() ([]byte, []int) {
	return fileDescriptor_384b7fc4eee58e57, []int{0}
}

func (m *EtcHost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EtcHost.Unmarshal(m, b)
}
func (m *EtcHost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EtcHost.Marshal(b, m, deterministic)
}
func (m *EtcHost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EtcHost.Merge(m, src)
}
func (m *EtcHost) XXX_Size() int {
	return xxx_messageInfo_EtcHost.Size(m)
}
func (m *EtcHost) XXX_DiscardUnknown() {
	xxx_messageInfo_EtcHost.DiscardUnknown(m)
}

var xxx_messageInfo_EtcHost proto.InternalMessageInfo

func (m *EtcHost) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EtcHost) GetHostnames() string {
	if m != nil {
		return m.Hostnames
	}
	return ""
}

func init() {
	proto.RegisterType((*EtcHost)(nil), "schemas.EtcHost")
}

func init() { proto.RegisterFile("pb/etc_host.proto", fileDescriptor_384b7fc4eee58e57) }

var fileDescriptor_384b7fc4eee58e57 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x48, 0xd2, 0x4f,
	0x2d, 0x49, 0x8e, 0xcf, 0xc8, 0x2f, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f,
	0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x2c, 0x56, 0x72, 0xe4, 0x62, 0x77, 0x2d, 0x49, 0xf6, 0xc8, 0x2f,
	0x2e, 0x11, 0x92, 0xe0, 0x62, 0x4f, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0x96, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x85, 0x64, 0xb8, 0x38, 0x41, 0x7a, 0xf3, 0x12, 0x73, 0x53, 0x8b,
	0x25, 0x98, 0xc0, 0x72, 0x08, 0x01, 0x27, 0xa3, 0x28, 0x83, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24,
	0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xdc, 0xcc, 0xe4, 0xec, 0xd4, 0x02, 0x73, 0x33, 0xfd, 0xfc, 0xe2,
	0xc2, 0xd2, 0xd4, 0xa2, 0x4a, 0x5d, 0xb0, 0x85, 0x49, 0xa5, 0x69, 0xfa, 0x05, 0xd9, 0xe9, 0xd6,
	0x50, 0x6b, 0x93, 0xd8, 0xc0, 0xa2, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x71, 0x4e,
	0x57, 0x9b, 0x00, 0x00, 0x00,
}
