// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/group.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Local system groups.
type Group struct {
	// Unsigned int64 group ID
	Gid uint64 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid"`
	// A signed int64 version of gid
	GidSigned int64 `protobuf:"varint,2,opt,name=gid_signed,json=gidSigned,proto3" json:"gid_signed"`
	// Canonical local group name
	Groupname string `protobuf:"bytes,3,opt,name=groupname,proto3" json:"groupname"`
	// Unique group ID
	GroupSid string `protobuf:"bytes,4,opt,name=group_sid,json=groupSid,proto3" json:"group_sid"`
	// Remarks or comments associated with the group
	Comment string `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment"`
	// IsHidden attribute set in OpenDirectory
	IsHidden             int32    `protobuf:"varint,6,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_291a6f2e016f8fe9, []int{0}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetGid() uint64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *Group) GetGidSigned() int64 {
	if m != nil {
		return m.GidSigned
	}
	return 0
}

func (m *Group) GetGroupname() string {
	if m != nil {
		return m.Groupname
	}
	return ""
}

func (m *Group) GetGroupSid() string {
	if m != nil {
		return m.GroupSid
	}
	return ""
}

func (m *Group) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Group) GetIsHidden() int32 {
	if m != nil {
		return m.IsHidden
	}
	return 0
}

func init() {
	proto.RegisterType((*Group)(nil), "schemas.Group")
}

func init() { proto.RegisterFile("pb/group.proto", fileDescriptor_291a6f2e016f8fe9) }

var fileDescriptor_291a6f2e016f8fe9 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x65, 0xd2, 0xb4, 0x8d, 0x07, 0x84, 0x3c, 0x59, 0x02, 0xa4, 0x88, 0x29, 0x0b, 0x0d,
	0x02, 0x09, 0x06, 0x36, 0x16, 0x98, 0xdd, 0x8d, 0x25, 0xaa, 0x7d, 0xc6, 0x39, 0x55, 0xfe, 0x43,
	0x1c, 0x0f, 0x7c, 0x25, 0x3e, 0x25, 0xca, 0xa9, 0xa8, 0xdb, 0xbd, 0xdf, 0x4f, 0xf7, 0xa4, 0xc7,
	0x2f, 0x93, 0xee, 0xdd, 0x14, 0x4b, 0xda, 0xa5, 0x29, 0xce, 0x51, 0x6c, 0xb2, 0x19, 0xad, 0x3f,
	0xe4, 0xbb, 0x5f, 0xc6, 0xeb, 0xf7, 0x45, 0x88, 0x2b, 0x5e, 0x39, 0x04, 0xc9, 0x5a, 0xd6, 0xad,
	0xd4, 0x72, 0x8a, 0x5b, 0xce, 0x1d, 0xc2, 0x90, 0xd1, 0x05, 0x0b, 0xf2, 0xa2, 0x65, 0x5d, 0xa5,
	0x1a, 0x87, 0xb0, 0x27, 0x20, 0x6e, 0x78, 0x43, 0x95, 0xe1, 0xe0, 0xad, 0xac, 0x5a, 0xd6, 0x35,
	0xea, 0x0c, 0xc4, 0xf5, 0xc9, 0x0e, 0x19, 0x41, 0xae, 0xc8, 0x6e, 0x09, 0xec, 0x11, 0x84, 0xe4,
	0x1b, 0x13, 0xbd, 0xb7, 0x61, 0x96, 0x35, 0xa9, 0xff, 0xb8, 0xbc, 0x61, 0x1e, 0x46, 0x04, 0xb0,
	0x41, 0xae, 0x5b, 0xd6, 0xd5, 0x6a, 0x8b, 0xf9, 0x83, 0xf2, 0xdb, 0xe3, 0xe7, 0x83, 0xc3, 0x79,
	0x2c, 0x7a, 0x67, 0xa2, 0xef, 0x3d, 0x9a, 0xa3, 0x4d, 0x2f, 0xcf, 0x7d, 0xcc, 0xdf, 0xc5, 0x4e,
	0x3f, 0xf7, 0x34, 0x4d, 0x97, 0xaf, 0x3e, 0x1d, 0xdd, 0xeb, 0x69, 0xa0, 0x5e, 0x13, 0x7d, 0xfa,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0x70, 0xe8, 0xec, 0xb9, 0x02, 0x01, 0x00, 0x00,
}
