// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/iokit_registry.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The full IOKit registry without selecting a plane.
type IokitRegistry struct {
	// Default name of the node
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	// Best matching device class (most-specific category)
	Class string `protobuf:"bytes,2,opt,name=class,proto3" json:"class"`
	// IOKit internal registry ID
	Id int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id"`
	// Parent registry ID
	Parent int64 `protobuf:"varint,4,opt,name=parent,proto3" json:"parent"`
	// 1 if the node is in a busy state else 0
	BusyState int32 `protobuf:"varint,5,opt,name=busy_state,json=busyState,proto3" json:"busy_state"`
	// The node reference count
	RetainCount int32 `protobuf:"varint,6,opt,name=retain_count,json=retainCount,proto3" json:"retain_count"`
	// Node nested depth
	Depth                int32    `protobuf:"varint,7,opt,name=depth,proto3" json:"depth"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IokitRegistry) Reset()         { *m = IokitRegistry{} }
func (m *IokitRegistry) String() string { return proto.CompactTextString(m) }
func (*IokitRegistry) ProtoMessage()    {}
func (*IokitRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_26c75382fe55cf55, []int{0}
}

func (m *IokitRegistry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IokitRegistry.Unmarshal(m, b)
}
func (m *IokitRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IokitRegistry.Marshal(b, m, deterministic)
}
func (m *IokitRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IokitRegistry.Merge(m, src)
}
func (m *IokitRegistry) XXX_Size() int {
	return xxx_messageInfo_IokitRegistry.Size(m)
}
func (m *IokitRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_IokitRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_IokitRegistry proto.InternalMessageInfo

func (m *IokitRegistry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IokitRegistry) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *IokitRegistry) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IokitRegistry) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *IokitRegistry) GetBusyState() int32 {
	if m != nil {
		return m.BusyState
	}
	return 0
}

func (m *IokitRegistry) GetRetainCount() int32 {
	if m != nil {
		return m.RetainCount
	}
	return 0
}

func (m *IokitRegistry) GetDepth() int32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func init() {
	proto.RegisterType((*IokitRegistry)(nil), "schemas.IokitRegistry")
}

func init() { proto.RegisterFile("pb/iokit_registry.proto", fileDescriptor_26c75382fe55cf55) }

var fileDescriptor_26c75382fe55cf55 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0xcf, 0x31, 0x4f, 0xbd, 0x30,
	0x14, 0x05, 0xf0, 0x94, 0xf7, 0xe0, 0xe5, 0xf5, 0xff, 0xd7, 0xa1, 0x31, 0xda, 0xc5, 0x04, 0x9d,
	0x58, 0x7c, 0x18, 0x4d, 0x74, 0x70, 0xd3, 0xc9, 0x15, 0x37, 0x17, 0xd2, 0x96, 0x2b, 0x34, 0x08,
	0xad, 0xed, 0xed, 0xc0, 0x47, 0xf3, 0xdb, 0x99, 0x16, 0xb6, 0x9e, 0x5f, 0x4f, 0x72, 0x73, 0xe8,
	0x95, 0x95, 0xb5, 0x36, 0xa3, 0xc6, 0xd6, 0x41, 0xaf, 0x3d, 0xba, 0xe5, 0x64, 0x9d, 0x41, 0xc3,
	0x0e, 0x5e, 0x0d, 0x30, 0x09, 0x7f, 0xfb, 0x4b, 0xe8, 0xd9, 0x7b, 0x6c, 0x34, 0x5b, 0x81, 0x31,
	0xba, 0x9f, 0xc5, 0x04, 0x9c, 0x94, 0xa4, 0x3a, 0x36, 0xe9, 0xcd, 0x2e, 0x68, 0xae, 0xbe, 0x85,
	0xf7, 0x3c, 0x4b, 0xb8, 0x06, 0x76, 0x4e, 0x33, 0xdd, 0xf1, 0x5d, 0x49, 0xaa, 0x5d, 0x93, 0xe9,
	0x8e, 0x5d, 0xd2, 0xc2, 0x0a, 0x07, 0x33, 0xf2, 0x7d, 0xb2, 0x2d, 0xb1, 0x6b, 0x4a, 0x65, 0xf0,
	0x4b, 0xeb, 0x51, 0x20, 0xf0, 0xbc, 0x24, 0x55, 0xde, 0x1c, 0xa3, 0x7c, 0x44, 0x60, 0x37, 0xf4,
	0xbf, 0x03, 0x14, 0x7a, 0x6e, 0x95, 0x09, 0x33, 0xf2, 0x22, 0x15, 0xfe, 0xad, 0xf6, 0x16, 0x29,
	0xde, 0xef, 0xc0, 0xe2, 0xc0, 0x0f, 0xe9, 0x6f, 0x0d, 0xaf, 0x0f, 0x9f, 0xf7, 0xbd, 0xc6, 0x21,
	0xc8, 0x93, 0x32, 0x53, 0x3d, 0x69, 0x35, 0x82, 0x7d, 0x7e, 0xaa, 0x8d, 0xff, 0x09, 0xe0, 0x96,
	0xbb, 0xb4, 0x54, 0x86, 0xaf, 0xda, 0x8e, 0xfd, 0xcb, 0xb6, 0x57, 0x16, 0x49, 0x1f, 0xff, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x60, 0x96, 0xfa, 0xd5, 0x1a, 0x01, 0x00, 0x00,
}
