// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/kernel_info.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Basic active kernel information.
type KernelInfo struct {
	// Kernel version
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version"`
	// Kernel arguments
	Arguments string `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments"`
	// Kernel path
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path"`
	// Kernel device identifier
	Device               string   `protobuf:"bytes,4,opt,name=device,proto3" json:"device"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KernelInfo) Reset()         { *m = KernelInfo{} }
func (m *KernelInfo) String() string { return proto.CompactTextString(m) }
func (*KernelInfo) ProtoMessage()    {}
func (*KernelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_03b187fe087a2311, []int{0}
}

func (m *KernelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KernelInfo.Unmarshal(m, b)
}
func (m *KernelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KernelInfo.Marshal(b, m, deterministic)
}
func (m *KernelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KernelInfo.Merge(m, src)
}
func (m *KernelInfo) XXX_Size() int {
	return xxx_messageInfo_KernelInfo.Size(m)
}
func (m *KernelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_KernelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_KernelInfo proto.InternalMessageInfo

func (m *KernelInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *KernelInfo) GetArguments() string {
	if m != nil {
		return m.Arguments
	}
	return ""
}

func (m *KernelInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *KernelInfo) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func init() {
	proto.RegisterType((*KernelInfo)(nil), "schemas.KernelInfo")
}

func init() { proto.RegisterFile("pb/kernel_info.proto", fileDescriptor_03b187fe087a2311) }

var fileDescriptor_03b187fe087a2311 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0x3d, 0xab, 0xc2, 0x30,
	0x18, 0x46, 0xe9, 0xbd, 0xa5, 0xa5, 0x19, 0xc3, 0xe5, 0x92, 0xc1, 0x41, 0x9c, 0x5c, 0x6c, 0x44,
	0x41, 0x07, 0x37, 0x37, 0x71, 0x73, 0x74, 0x91, 0x26, 0xbe, 0x6d, 0x43, 0xcd, 0x87, 0xf9, 0x28,
	0xf8, 0xef, 0x85, 0x97, 0x8a, 0xdb, 0xf3, 0x9c, 0xb3, 0x1c, 0xf2, 0xe7, 0x04, 0x1f, 0xc0, 0x1b,
	0x78, 0xdc, 0x94, 0x69, 0x6d, 0xed, 0xbc, 0x8d, 0x96, 0x96, 0x41, 0xf6, 0xa0, 0x9b, 0xb0, 0x70,
	0x84, 0x9c, 0xd1, 0x9e, 0x4c, 0x6b, 0x29, 0x23, 0xe5, 0x08, 0x3e, 0x28, 0x6b, 0x58, 0x36, 0xcf,
	0x96, 0xd5, 0xe5, 0x73, 0xe9, 0x8c, 0x54, 0x8d, 0xef, 0x92, 0x06, 0x13, 0x03, 0xfb, 0x41, 0xf7,
	0x05, 0x94, 0x92, 0xdc, 0x35, 0xb1, 0x67, 0xbf, 0x28, 0x70, 0xd3, 0x7f, 0x52, 0xdc, 0x61, 0x54,
	0x12, 0x58, 0x8e, 0x74, 0x7a, 0xc7, 0xcd, 0x75, 0xdd, 0xa9, 0xd8, 0x27, 0x51, 0x4b, 0xab, 0xb9,
	0x56, 0x72, 0x00, 0xb7, 0xdf, 0x71, 0x1b, 0x9e, 0x09, 0xfc, 0x6b, 0x85, 0x7d, 0x22, 0xb5, 0xdc,
	0x0d, 0xdd, 0x61, 0xaa, 0x14, 0x05, 0xd2, 0xed, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xb8, 0xd0,
	0x3e, 0xcd, 0x00, 0x00, 0x00,
}
