// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/keychain_item.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Generic details about keychain items.
type KeychainItem struct {
	// Generic item name
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label"`
	// Optional item description
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description"`
	// Optional keychain comment
	Comment string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment"`
	// Data item was created
	Created string `protobuf:"bytes,4,opt,name=created,proto3" json:"created"`
	// Date of last modification
	Modified string `protobuf:"bytes,5,opt,name=modified,proto3" json:"modified"`
	// Keychain item type (class)
	Type string `protobuf:"bytes,6,opt,name=type,proto3" json:"type"`
	// Path to keychain containing item
	Path                 string   `protobuf:"bytes,7,opt,name=path,proto3" json:"path"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeychainItem) Reset()         { *m = KeychainItem{} }
func (m *KeychainItem) String() string { return proto.CompactTextString(m) }
func (*KeychainItem) ProtoMessage()    {}
func (*KeychainItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_a62190c205003873, []int{0}
}

func (m *KeychainItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeychainItem.Unmarshal(m, b)
}
func (m *KeychainItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeychainItem.Marshal(b, m, deterministic)
}
func (m *KeychainItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeychainItem.Merge(m, src)
}
func (m *KeychainItem) XXX_Size() int {
	return xxx_messageInfo_KeychainItem.Size(m)
}
func (m *KeychainItem) XXX_DiscardUnknown() {
	xxx_messageInfo_KeychainItem.DiscardUnknown(m)
}

var xxx_messageInfo_KeychainItem proto.InternalMessageInfo

func (m *KeychainItem) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *KeychainItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *KeychainItem) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *KeychainItem) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *KeychainItem) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *KeychainItem) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *KeychainItem) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*KeychainItem)(nil), "schemas.KeychainItem")
}

func init() { proto.RegisterFile("pb/keychain_item.proto", fileDescriptor_a62190c205003873) }

var fileDescriptor_a62190c205003873 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x46, 0x15, 0x68, 0x1b, 0x30, 0x4c, 0x16, 0x42, 0x27, 0xa6, 0x8a, 0x89, 0x85, 0x06, 0x81,
	0x04, 0x03, 0x1b, 0x1b, 0x62, 0x63, 0x64, 0x41, 0xb6, 0x73, 0x6d, 0x4e, 0xe9, 0xc5, 0x26, 0xbe,
	0x0c, 0xf9, 0x73, 0xfc, 0x36, 0xd4, 0x4b, 0x40, 0x6c, 0xf7, 0xde, 0xbb, 0xe5, 0x33, 0x97, 0xc9,
	0x57, 0x2d, 0x8e, 0xa1, 0x71, 0xd4, 0x7d, 0x92, 0x20, 0x6f, 0x52, 0x1f, 0x25, 0xda, 0x32, 0x87,
	0x06, 0xd9, 0xe5, 0xeb, 0xef, 0xc2, 0x9c, 0xbf, 0xcd, 0x0f, 0xaf, 0x82, 0x6c, 0x2f, 0xcc, 0x72,
	0xef, 0x3c, 0xee, 0xa1, 0x58, 0x17, 0x37, 0xa7, 0xef, 0x13, 0xd8, 0xb5, 0x39, 0xab, 0x31, 0x87,
	0x9e, 0x92, 0x50, 0xec, 0xe0, 0x48, 0xdb, 0x7f, 0x65, 0xc1, 0x94, 0x21, 0x32, 0x63, 0x27, 0x70,
	0xac, 0xf5, 0x17, 0xb5, 0xf4, 0xe8, 0x04, 0x6b, 0x58, 0xcc, 0x65, 0x42, 0x7b, 0x65, 0x4e, 0x38,
	0xd6, 0xb4, 0x25, 0xac, 0x61, 0xa9, 0xe9, 0x8f, 0xad, 0x35, 0x0b, 0x19, 0x13, 0xc2, 0x4a, 0xbd,
	0xde, 0x07, 0x97, 0x9c, 0x34, 0x50, 0x4e, 0xee, 0x70, 0xbf, 0xdc, 0x7f, 0xdc, 0xed, 0x48, 0x9a,
	0xc1, 0x6f, 0x42, 0xe4, 0x8a, 0x29, 0xb4, 0x98, 0x9e, 0x1e, 0xab, 0x98, 0xbf, 0x06, 0xec, 0xc7,
	0x5b, 0x9d, 0xeb, 0x87, 0x6d, 0x95, 0xda, 0xdd, 0xf3, 0x3c, 0xda, 0xaf, 0xd4, 0x3e, 0xfc, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x07, 0x3e, 0x1f, 0x50, 0x1e, 0x01, 0x00, 0x00,
}
