// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/md_personality.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Software RAID setting supported by the kernel.
type MdPersonality struct {
	// Name of personality supported by kernel
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MdPersonality) Reset()         { *m = MdPersonality{} }
func (m *MdPersonality) String() string { return proto.CompactTextString(m) }
func (*MdPersonality) ProtoMessage()    {}
func (*MdPersonality) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb31ae5b55759297, []int{0}
}

func (m *MdPersonality) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MdPersonality.Unmarshal(m, b)
}
func (m *MdPersonality) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MdPersonality.Marshal(b, m, deterministic)
}
func (m *MdPersonality) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MdPersonality.Merge(m, src)
}
func (m *MdPersonality) XXX_Size() int {
	return xxx_messageInfo_MdPersonality.Size(m)
}
func (m *MdPersonality) XXX_DiscardUnknown() {
	xxx_messageInfo_MdPersonality.DiscardUnknown(m)
}

var xxx_messageInfo_MdPersonality proto.InternalMessageInfo

func (m *MdPersonality) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*MdPersonality)(nil), "schemas.MdPersonality")
}

func init() { proto.RegisterFile("pb/md_personality.proto", fileDescriptor_eb31ae5b55759297) }

var fileDescriptor_eb31ae5b55759297 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x48, 0xd2, 0xcf,
	0x4d, 0x89, 0x2f, 0x48, 0x2d, 0x2a, 0xce, 0xcf, 0x4b, 0xcc, 0xc9, 0x2c, 0xa9, 0xd4, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x2c, 0x56, 0x52, 0xe6, 0xe2,
	0xf5, 0x4d, 0x09, 0x40, 0xc8, 0x0b, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x4e, 0x46, 0x51, 0x06, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49,
	0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0xb9, 0x99, 0xc9, 0xd9, 0xa9, 0x05, 0xe6, 0x66, 0xfa, 0xf9, 0xc5,
	0x85, 0xa5, 0xa9, 0x45, 0x95, 0xba, 0x60, 0x23, 0x93, 0x4a, 0xd3, 0xf4, 0x0b, 0xb2, 0xd3, 0xad,
	0xa1, 0x06, 0x27, 0xb1, 0x81, 0x45, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x64, 0x84,
	0x18, 0x83, 0x00, 0x00, 0x00,
}
