// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/mdfind.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Run searches against the spotlight database.
type Mdfind struct {
	// Path of the file returned from spotlight
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path"`
	// The query that was run to find the file
	Query                string   `protobuf:"bytes,2,opt,name=query,proto3" json:"query"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mdfind) Reset()         { *m = Mdfind{} }
func (m *Mdfind) String() string { return proto.CompactTextString(m) }
func (*Mdfind) ProtoMessage()    {}
func (*Mdfind) Descriptor() ([]byte, []int) {
	return fileDescriptor_42db6ed62a45de72, []int{0}
}

func (m *Mdfind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mdfind.Unmarshal(m, b)
}
func (m *Mdfind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mdfind.Marshal(b, m, deterministic)
}
func (m *Mdfind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mdfind.Merge(m, src)
}
func (m *Mdfind) XXX_Size() int {
	return xxx_messageInfo_Mdfind.Size(m)
}
func (m *Mdfind) XXX_DiscardUnknown() {
	xxx_messageInfo_Mdfind.DiscardUnknown(m)
}

var xxx_messageInfo_Mdfind proto.InternalMessageInfo

func (m *Mdfind) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Mdfind) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func init() {
	proto.RegisterType((*Mdfind)(nil), "schemas.Mdfind")
}

func init() { proto.RegisterFile("pb/mdfind.proto", fileDescriptor_42db6ed62a45de72) }

var fileDescriptor_42db6ed62a45de72 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x48, 0xd2, 0xcf,
	0x4d, 0x49, 0xcb, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0xce,
	0x48, 0xcd, 0x4d, 0x2c, 0x56, 0x32, 0xe2, 0x62, 0xf3, 0x05, 0x4b, 0x08, 0x09, 0x71, 0xb1, 0x14,
	0x24, 0x96, 0x64, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac,
	0x85, 0xa5, 0xa9, 0x45, 0x95, 0x12, 0x4c, 0x60, 0x41, 0x08, 0xc7, 0xc9, 0x28, 0xca, 0x20, 0x3d,
	0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x3f, 0x37, 0x33, 0x39, 0x3b, 0xb5, 0xc0,
	0xdc, 0x4c, 0x3f, 0xbf, 0x18, 0x2c, 0xad, 0x0b, 0xb6, 0x21, 0xa9, 0x34, 0x4d, 0xbf, 0x20, 0x3b,
	0xdd, 0x1a, 0x6a, 0x4f, 0x12, 0x1b, 0x58, 0xd4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x95, 0x05,
	0x0e, 0x08, 0x8a, 0x00, 0x00, 0x00,
}
