// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/memory_map.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// OS memory region map.
type MemoryMap struct {
	// Region name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	// Start address of memory region
	Start string `protobuf:"bytes,2,opt,name=start,proto3" json:"start"`
	// End address of memory region
	End                  string   `protobuf:"bytes,3,opt,name=end,proto3" json:"end"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryMap) Reset()         { *m = MemoryMap{} }
func (m *MemoryMap) String() string { return proto.CompactTextString(m) }
func (*MemoryMap) ProtoMessage()    {}
func (*MemoryMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_87835b965944d8dc, []int{0}
}

func (m *MemoryMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryMap.Unmarshal(m, b)
}
func (m *MemoryMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryMap.Marshal(b, m, deterministic)
}
func (m *MemoryMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryMap.Merge(m, src)
}
func (m *MemoryMap) XXX_Size() int {
	return xxx_messageInfo_MemoryMap.Size(m)
}
func (m *MemoryMap) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryMap.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryMap proto.InternalMessageInfo

func (m *MemoryMap) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MemoryMap) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *MemoryMap) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func init() {
	proto.RegisterType((*MemoryMap)(nil), "schemas.MemoryMap")
}

func init() { proto.RegisterFile("pb/memory_map.proto", fileDescriptor_87835b965944d8dc) }

var fileDescriptor_87835b965944d8dc = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x48, 0xd2, 0xcf,
	0x4d, 0xcd, 0xcd, 0x2f, 0xaa, 0x8c, 0xcf, 0x4d, 0x2c, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x2c, 0x56, 0x72, 0xe7, 0xe2, 0xf4, 0x05, 0x4b, 0xfa,
	0x26, 0x16, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac, 0xc5, 0x25, 0x89, 0x45, 0x25, 0x12, 0x4c, 0x60, 0x41,
	0x08, 0x47, 0x48, 0x80, 0x8b, 0x39, 0x35, 0x2f, 0x45, 0x82, 0x19, 0x2c, 0x06, 0x62, 0x3a, 0x19,
	0x45, 0x19, 0xa4, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xe7, 0x66, 0x26,
	0x67, 0xa7, 0x16, 0x98, 0x9b, 0xe9, 0xe7, 0x17, 0x17, 0x96, 0xa6, 0x16, 0x55, 0xea, 0x82, 0xad,
	0x4d, 0x2a, 0x4d, 0xd3, 0x2f, 0xc8, 0x4e, 0xb7, 0x86, 0x5a, 0x9e, 0xc4, 0x06, 0x16, 0x35, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x35, 0xd9, 0x38, 0x82, 0xa3, 0x00, 0x00, 0x00,
}
