// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/nfs_share.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// NFS shares exported by the host.
type NfsShare struct {
	// Filesystem path to the share
	Share string `protobuf:"bytes,1,opt,name=share,proto3" json:"share"`
	// Options string set on the export share
	Options string `protobuf:"bytes,2,opt,name=options,proto3" json:"options"`
	// 1 if the share is exported readonly else 0
	Readonly             int32    `protobuf:"varint,3,opt,name=readonly,proto3" json:"readonly"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NfsShare) Reset()         { *m = NfsShare{} }
func (m *NfsShare) String() string { return proto.CompactTextString(m) }
func (*NfsShare) ProtoMessage()    {}
func (*NfsShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_702a679633d7e52a, []int{0}
}

func (m *NfsShare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NfsShare.Unmarshal(m, b)
}
func (m *NfsShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NfsShare.Marshal(b, m, deterministic)
}
func (m *NfsShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NfsShare.Merge(m, src)
}
func (m *NfsShare) XXX_Size() int {
	return xxx_messageInfo_NfsShare.Size(m)
}
func (m *NfsShare) XXX_DiscardUnknown() {
	xxx_messageInfo_NfsShare.DiscardUnknown(m)
}

var xxx_messageInfo_NfsShare proto.InternalMessageInfo

func (m *NfsShare) GetShare() string {
	if m != nil {
		return m.Share
	}
	return ""
}

func (m *NfsShare) GetOptions() string {
	if m != nil {
		return m.Options
	}
	return ""
}

func (m *NfsShare) GetReadonly() int32 {
	if m != nil {
		return m.Readonly
	}
	return 0
}

func init() {
	proto.RegisterType((*NfsShare)(nil), "schemas.NfsShare")
}

func init() { proto.RegisterFile("pb/nfs_share.proto", fileDescriptor_702a679633d7e52a) }

var fileDescriptor_702a679633d7e52a = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x48, 0xd2, 0xcf,
	0x4b, 0x2b, 0x8e, 0x2f, 0xce, 0x48, 0x2c, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x2c, 0x56, 0x0a, 0xe3, 0xe2, 0xf0, 0x4b, 0x2b, 0x0e, 0x06,
	0x49, 0x09, 0x89, 0x70, 0xb1, 0x82, 0xd5, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38,
	0x42, 0x12, 0x5c, 0xec, 0xf9, 0x05, 0x25, 0x99, 0xf9, 0x79, 0xc5, 0x12, 0x4c, 0x60, 0x71, 0x18,
	0x57, 0x48, 0x8a, 0x8b, 0xa3, 0x28, 0x35, 0x31, 0x25, 0x3f, 0x2f, 0xa7, 0x52, 0x82, 0x59, 0x81,
	0x51, 0x83, 0x35, 0x08, 0xce, 0x77, 0x32, 0x8a, 0x32, 0x48, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2,
	0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xcd, 0x4c, 0xce, 0x4e, 0x2d, 0x30, 0x37, 0xd3, 0xcf, 0x2f, 0x2e,
	0x2c, 0x4d, 0x2d, 0xaa, 0xd4, 0x05, 0xbb, 0x22, 0xa9, 0x34, 0x4d, 0xbf, 0x20, 0x3b, 0xdd, 0x1a,
	0xea, 0x96, 0x24, 0x36, 0xb0, 0xa8, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x98, 0xf8, 0x30, 0x2b,
	0xb1, 0x00, 0x00, 0x00,
}
