// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/nvram.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Apple NVRAM variable listing.
type Nvram struct {
	// Variable name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	// Data type (CFData
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type"`
	// Raw variable data
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nvram) Reset()         { *m = Nvram{} }
func (m *Nvram) String() string { return proto.CompactTextString(m) }
func (*Nvram) ProtoMessage()    {}
func (*Nvram) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ab5b0f084e231c, []int{0}
}

func (m *Nvram) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nvram.Unmarshal(m, b)
}
func (m *Nvram) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nvram.Marshal(b, m, deterministic)
}
func (m *Nvram) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nvram.Merge(m, src)
}
func (m *Nvram) XXX_Size() int {
	return xxx_messageInfo_Nvram.Size(m)
}
func (m *Nvram) XXX_DiscardUnknown() {
	xxx_messageInfo_Nvram.DiscardUnknown(m)
}

var xxx_messageInfo_Nvram proto.InternalMessageInfo

func (m *Nvram) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Nvram) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Nvram) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Nvram)(nil), "schemas.Nvram")
}

func init() { proto.RegisterFile("pb/nvram.proto", fileDescriptor_64ab5b0f084e231c) }

var fileDescriptor_64ab5b0f084e231c = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x48, 0xd2, 0xcf,
	0x2b, 0x2b, 0x4a, 0xcc, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0xce, 0x48,
	0xcd, 0x4d, 0x2c, 0x56, 0x72, 0xe5, 0x62, 0xf5, 0x03, 0x89, 0x0b, 0x09, 0x71, 0xb1, 0xe4, 0x25,
	0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x20, 0xb1, 0x92, 0xca, 0x82,
	0x54, 0x09, 0x26, 0x88, 0x18, 0x88, 0x2d, 0x24, 0xc2, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a, 0x2a,
	0xc1, 0x0c, 0x16, 0x84, 0x70, 0x9c, 0x8c, 0xa2, 0x0c, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4,
	0x92, 0xf3, 0x73, 0xf5, 0x73, 0x33, 0x93, 0xb3, 0x53, 0x0b, 0xcc, 0xcd, 0xf4, 0xf3, 0x8b, 0x0b,
	0x4b, 0x53, 0x8b, 0x2a, 0x75, 0xc1, 0x96, 0x26, 0x95, 0xa6, 0xe9, 0x17, 0x64, 0xa7, 0x5b, 0x43,
	0xad, 0x4e, 0x62, 0x03, 0x8b, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x49, 0x7e, 0x22, 0x2c,
	0x9c, 0x00, 0x00, 0x00,
}
