// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/pipe.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Named and Anonymous pipes.
type Pipe struct {
	// Process ID of the process to which the pipe belongs
	Pid int64 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid"`
	// Name of the pipe
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	// Number of instances of the named pipe
	Instances int32 `protobuf:"varint,3,opt,name=instances,proto3" json:"instances"`
	// The maximum number of instances creatable for this pipe
	MaxInstances int32 `protobuf:"varint,4,opt,name=max_instances,json=maxInstances,proto3" json:"max_instances"`
	// The flags indicating whether this pipe connection is a server or client end
	Flags                string   `protobuf:"bytes,5,opt,name=flags,proto3" json:"flags"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pipe) Reset()         { *m = Pipe{} }
func (m *Pipe) String() string { return proto.CompactTextString(m) }
func (*Pipe) ProtoMessage()    {}
func (*Pipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_e02327e08fc0067b, []int{0}
}

func (m *Pipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pipe.Unmarshal(m, b)
}
func (m *Pipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pipe.Marshal(b, m, deterministic)
}
func (m *Pipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pipe.Merge(m, src)
}
func (m *Pipe) XXX_Size() int {
	return xxx_messageInfo_Pipe.Size(m)
}
func (m *Pipe) XXX_DiscardUnknown() {
	xxx_messageInfo_Pipe.DiscardUnknown(m)
}

var xxx_messageInfo_Pipe proto.InternalMessageInfo

func (m *Pipe) GetPid() int64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Pipe) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pipe) GetInstances() int32 {
	if m != nil {
		return m.Instances
	}
	return 0
}

func (m *Pipe) GetMaxInstances() int32 {
	if m != nil {
		return m.MaxInstances
	}
	return 0
}

func (m *Pipe) GetFlags() string {
	if m != nil {
		return m.Flags
	}
	return ""
}

func init() {
	proto.RegisterType((*Pipe)(nil), "schemas.Pipe")
}

func init() { proto.RegisterFile("pb/pipe.proto", fileDescriptor_e02327e08fc0067b) }

var fileDescriptor_e02327e08fc0067b = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x48, 0xd2, 0x2f,
	0xc8, 0x2c, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0xce, 0x48, 0xcd,
	0x4d, 0x2c, 0x56, 0x6a, 0x65, 0xe4, 0x62, 0x09, 0xc8, 0x2c, 0x48, 0x15, 0x12, 0xe0, 0x62, 0x2e,
	0xc8, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x02, 0x31, 0x85, 0x84, 0xb8, 0x58, 0xf2,
	0x12, 0x73, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x19, 0x2e, 0xce,
	0xcc, 0xbc, 0xe2, 0x92, 0xc4, 0xbc, 0xe4, 0xd4, 0x62, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xd6, 0x20,
	0x84, 0x80, 0x90, 0x32, 0x17, 0x6f, 0x6e, 0x62, 0x45, 0x3c, 0x42, 0x05, 0x0b, 0x58, 0x05, 0x4f,
	0x6e, 0x62, 0x85, 0x27, 0x5c, 0x91, 0x08, 0x17, 0x6b, 0x5a, 0x4e, 0x62, 0x7a, 0xb1, 0x04, 0x2b,
	0xd8, 0x5c, 0x08, 0xc7, 0xc9, 0x28, 0xca, 0x20, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39,
	0x3f, 0x57, 0x3f, 0x37, 0x33, 0x39, 0x3b, 0xb5, 0xc0, 0xdc, 0x4c, 0x3f, 0xbf, 0xb8, 0xb0, 0x34,
	0xb5, 0xa8, 0x52, 0x17, 0xec, 0xea, 0xa4, 0xd2, 0x34, 0xfd, 0x82, 0xec, 0x74, 0x6b, 0xa8, 0xdb,
	0x93, 0xd8, 0xc0, 0xa2, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x81, 0xb8, 0x98, 0xfd, 0xdc,
	0x00, 0x00, 0x00,
}
