// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/portage_keyword.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A summary about portage configurations like keywords, mask and unmask.
type PortageKeyword struct {
	// Package name
	Package string `protobuf:"bytes,1,opt,name=package,proto3" json:"package"`
	// The version which are affected by the use flags
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version"`
	// The keyword applied to the package
	Keyword string `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword"`
	// If the package is masked
	Mask int32 `protobuf:"varint,4,opt,name=mask,proto3" json:"mask"`
	// If the package is unmasked
	Unmask               int32    `protobuf:"varint,5,opt,name=unmask,proto3" json:"unmask"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PortageKeyword) Reset()         { *m = PortageKeyword{} }
func (m *PortageKeyword) String() string { return proto.CompactTextString(m) }
func (*PortageKeyword) ProtoMessage()    {}
func (*PortageKeyword) Descriptor() ([]byte, []int) {
	return fileDescriptor_03e12dc170d2c499, []int{0}
}

func (m *PortageKeyword) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortageKeyword.Unmarshal(m, b)
}
func (m *PortageKeyword) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortageKeyword.Marshal(b, m, deterministic)
}
func (m *PortageKeyword) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortageKeyword.Merge(m, src)
}
func (m *PortageKeyword) XXX_Size() int {
	return xxx_messageInfo_PortageKeyword.Size(m)
}
func (m *PortageKeyword) XXX_DiscardUnknown() {
	xxx_messageInfo_PortageKeyword.DiscardUnknown(m)
}

var xxx_messageInfo_PortageKeyword proto.InternalMessageInfo

func (m *PortageKeyword) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *PortageKeyword) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PortageKeyword) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *PortageKeyword) GetMask() int32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

func (m *PortageKeyword) GetUnmask() int32 {
	if m != nil {
		return m.Unmask
	}
	return 0
}

func init() {
	proto.RegisterType((*PortageKeyword)(nil), "schemas.PortageKeyword")
}

func init() { proto.RegisterFile("pb/portage_keyword.proto", fileDescriptor_03e12dc170d2c499) }

var fileDescriptor_03e12dc170d2c499 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x48, 0xd2, 0x2f,
	0xc8, 0x2f, 0x2a, 0x49, 0x4c, 0x4f, 0x8d, 0xcf, 0x4e, 0xad, 0x2c, 0xcf, 0x2f, 0x4a, 0xd1, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x2c, 0x56, 0xea, 0x62,
	0xe4, 0xe2, 0x0b, 0x80, 0x28, 0xf1, 0x86, 0xa8, 0x10, 0x92, 0xe0, 0x62, 0x2f, 0x48, 0x4c, 0xce,
	0x4e, 0x4c, 0x4f, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x41, 0x32, 0x65, 0xa9,
	0x45, 0xc5, 0x99, 0xf9, 0x79, 0x12, 0x4c, 0x10, 0x19, 0x28, 0x17, 0x24, 0x03, 0xb5, 0x40, 0x82,
	0x19, 0x22, 0x03, 0xe5, 0x0a, 0x09, 0x71, 0xb1, 0xe4, 0x26, 0x16, 0x67, 0x4b, 0xb0, 0x28, 0x30,
	0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x42, 0x62, 0x5c, 0x6c, 0xa5, 0x79, 0x60, 0x51, 0x56, 0xb0, 0x28,
	0x94, 0xe7, 0x64, 0x14, 0x65, 0x90, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab,
	0x9f, 0x9b, 0x99, 0x9c, 0x9d, 0x5a, 0x60, 0x6e, 0xa6, 0x9f, 0x5f, 0x5c, 0x58, 0x9a, 0x5a, 0x54,
	0xa9, 0x0b, 0x76, 0x7a, 0x52, 0x69, 0x9a, 0x7e, 0x41, 0x76, 0xba, 0x35, 0xd4, 0x03, 0x49, 0x6c,
	0x60, 0x51, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x66, 0xb6, 0xf5, 0xec, 0x00, 0x00,
	0x00,
}
