// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/portage_package.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// List of currently installed packages.
type PortagePackage struct {
	// Package name
	Package string `protobuf:"bytes,1,opt,name=package,proto3" json:"package"`
	// The version which are affected by the use flags
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version"`
	// The slot used by package
	Slot string `protobuf:"bytes,3,opt,name=slot,proto3" json:"slot"`
	// Unix time when package was built
	BuildTime int64 `protobuf:"varint,4,opt,name=build_time,json=buildTime,proto3" json:"build_time"`
	// From which repository the ebuild was used
	Repository string `protobuf:"bytes,5,opt,name=repository,proto3" json:"repository"`
	// The eapi for the ebuild
	Eapi int64 `protobuf:"varint,6,opt,name=eapi,proto3" json:"eapi"`
	// The size of the package
	Size int64 `protobuf:"varint,7,opt,name=size,proto3" json:"size"`
	// If package is in the world file
	World                int32    `protobuf:"varint,8,opt,name=world,proto3" json:"world"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PortagePackage) Reset()         { *m = PortagePackage{} }
func (m *PortagePackage) String() string { return proto.CompactTextString(m) }
func (*PortagePackage) ProtoMessage()    {}
func (*PortagePackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_51ee4f67577d5a6a, []int{0}
}

func (m *PortagePackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortagePackage.Unmarshal(m, b)
}
func (m *PortagePackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortagePackage.Marshal(b, m, deterministic)
}
func (m *PortagePackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortagePackage.Merge(m, src)
}
func (m *PortagePackage) XXX_Size() int {
	return xxx_messageInfo_PortagePackage.Size(m)
}
func (m *PortagePackage) XXX_DiscardUnknown() {
	xxx_messageInfo_PortagePackage.DiscardUnknown(m)
}

var xxx_messageInfo_PortagePackage proto.InternalMessageInfo

func (m *PortagePackage) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *PortagePackage) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PortagePackage) GetSlot() string {
	if m != nil {
		return m.Slot
	}
	return ""
}

func (m *PortagePackage) GetBuildTime() int64 {
	if m != nil {
		return m.BuildTime
	}
	return 0
}

func (m *PortagePackage) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *PortagePackage) GetEapi() int64 {
	if m != nil {
		return m.Eapi
	}
	return 0
}

func (m *PortagePackage) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PortagePackage) GetWorld() int32 {
	if m != nil {
		return m.World
	}
	return 0
}

func init() {
	proto.RegisterType((*PortagePackage)(nil), "schemas.PortagePackage")
}

func init() { proto.RegisterFile("pb/portage_package.proto", fileDescriptor_51ee4f67577d5a6a) }

var fileDescriptor_51ee4f67577d5a6a = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x15, 0xda, 0x34, 0xd4, 0x03, 0x83, 0xc5, 0x70, 0x0b, 0x28, 0x62, 0xca, 0x42, 0x83,
	0x40, 0x82, 0x81, 0x8d, 0x5f, 0x50, 0x45, 0x4c, 0x2c, 0x95, 0x9d, 0x1e, 0xa9, 0x95, 0x98, 0x33,
	0xb6, 0x03, 0x2a, 0xff, 0x93, 0xff, 0x83, 0x72, 0x0e, 0x52, 0xb7, 0xf7, 0xbe, 0x7b, 0xcf, 0x96,
	0x9e, 0x00, 0xa7, 0x6b, 0x47, 0x3e, 0xaa, 0x0e, 0x77, 0x4e, 0xb5, 0xbd, 0xea, 0x70, 0xe3, 0x3c,
	0x45, 0x92, 0x45, 0x68, 0x0f, 0x68, 0x55, 0xb8, 0xf9, 0xcd, 0xc4, 0xc5, 0x36, 0x45, 0xb6, 0x29,
	0x21, 0x41, 0x14, 0x73, 0x18, 0xb2, 0x32, 0xab, 0xd6, 0xcd, 0xbf, 0x9d, 0x2e, 0x5f, 0xe8, 0x83,
	0xa1, 0x0f, 0x38, 0x4b, 0x97, 0xd9, 0x4a, 0x29, 0x96, 0x61, 0xa0, 0x08, 0x0b, 0xc6, 0xac, 0xe5,
	0x95, 0x10, 0x7a, 0x34, 0xc3, 0x7e, 0x17, 0x8d, 0x45, 0x58, 0x96, 0x59, 0xb5, 0x68, 0xd6, 0x4c,
	0x5e, 0x8d, 0x45, 0x79, 0x2d, 0x84, 0x47, 0x47, 0xc1, 0x44, 0xf2, 0x47, 0xc8, 0xb9, 0x78, 0x42,
	0xa6, 0x27, 0x51, 0x39, 0x03, 0x2b, 0x2e, 0xb2, 0xe6, 0x6f, 0xcc, 0x0f, 0x42, 0x91, 0xd8, 0xa4,
	0xe5, 0xa5, 0xc8, 0xbf, 0xc9, 0x0f, 0x7b, 0x38, 0x2f, 0xb3, 0x2a, 0x6f, 0x92, 0x79, 0xb9, 0x7f,
	0xbb, 0xeb, 0x4c, 0x3c, 0x8c, 0x7a, 0xd3, 0x92, 0xad, 0xad, 0x69, 0x7b, 0x74, 0x4f, 0x8f, 0x35,
	0x85, 0xcf, 0x11, 0xfd, 0xf1, 0x96, 0x57, 0xd0, 0xe3, 0x7b, 0xed, 0xfa, 0xee, 0x79, 0xde, 0x42,
	0xaf, 0x98, 0x3e, 0xfc, 0x05, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x3b, 0x8c, 0xfe, 0x37, 0x01, 0x00,
	0x00,
}
