// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/process_env.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A key/value table of environment variables for each process.
type ProcessEnv struct {
	// Process (or thread) ID
	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid"`
	// Environment variable name
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key"`
	// Environment variable value
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessEnv) Reset()         { *m = ProcessEnv{} }
func (m *ProcessEnv) String() string { return proto.CompactTextString(m) }
func (*ProcessEnv) ProtoMessage()    {}
func (*ProcessEnv) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a72ccd6fa6ee5fc, []int{0}
}

func (m *ProcessEnv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessEnv.Unmarshal(m, b)
}
func (m *ProcessEnv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessEnv.Marshal(b, m, deterministic)
}
func (m *ProcessEnv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessEnv.Merge(m, src)
}
func (m *ProcessEnv) XXX_Size() int {
	return xxx_messageInfo_ProcessEnv.Size(m)
}
func (m *ProcessEnv) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessEnv.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessEnv proto.InternalMessageInfo

func (m *ProcessEnv) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *ProcessEnv) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ProcessEnv) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*ProcessEnv)(nil), "schemas.ProcessEnv")
}

func init() { proto.RegisterFile("pb/process_env.proto", fileDescriptor_3a72ccd6fa6ee5fc) }

var fileDescriptor_3a72ccd6fa6ee5fc = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x48, 0xd2, 0x2f,
	0x28, 0xca, 0x4f, 0x4e, 0x2d, 0x2e, 0x8e, 0x4f, 0xcd, 0x2b, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x2c, 0x56, 0x72, 0xe3, 0xe2, 0x0a, 0x80, 0xc8,
	0xba, 0xe6, 0x95, 0x09, 0x09, 0x70, 0x31, 0x17, 0x64, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0,
	0x06, 0x81, 0x98, 0x20, 0x91, 0xec, 0xd4, 0x4a, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10,
	0x53, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x19, 0x2c, 0x06, 0xe1, 0x38,
	0x19, 0x45, 0x19, 0xa4, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xe7, 0x66,
	0x26, 0x67, 0xa7, 0x16, 0x98, 0x9b, 0xe9, 0xe7, 0x17, 0x17, 0x96, 0xa6, 0x16, 0x55, 0xea, 0x82,
	0x6d, 0x4d, 0x2a, 0x4d, 0xd3, 0x2f, 0xc8, 0x4e, 0xb7, 0x86, 0xda, 0x9d, 0xc4, 0x06, 0x16, 0x35,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xf4, 0x71, 0xca, 0xa3, 0x00, 0x00, 0x00,
}
