// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/process_open_file.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// File descriptors for each process.
type ProcessOpenFile struct {
	// Process (or thread) ID
	Pid int64 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid"`
	// Process-specific file descriptor number
	Fd int64 `protobuf:"varint,2,opt,name=fd,proto3" json:"fd"`
	// Filesystem path of descriptor
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessOpenFile) Reset()         { *m = ProcessOpenFile{} }
func (m *ProcessOpenFile) String() string { return proto.CompactTextString(m) }
func (*ProcessOpenFile) ProtoMessage()    {}
func (*ProcessOpenFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77ce72cb4764193, []int{0}
}

func (m *ProcessOpenFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessOpenFile.Unmarshal(m, b)
}
func (m *ProcessOpenFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessOpenFile.Marshal(b, m, deterministic)
}
func (m *ProcessOpenFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessOpenFile.Merge(m, src)
}
func (m *ProcessOpenFile) XXX_Size() int {
	return xxx_messageInfo_ProcessOpenFile.Size(m)
}
func (m *ProcessOpenFile) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessOpenFile.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessOpenFile proto.InternalMessageInfo

func (m *ProcessOpenFile) GetPid() int64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *ProcessOpenFile) GetFd() int64 {
	if m != nil {
		return m.Fd
	}
	return 0
}

func (m *ProcessOpenFile) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*ProcessOpenFile)(nil), "schemas.ProcessOpenFile")
}

func init() { proto.RegisterFile("pb/process_open_file.proto", fileDescriptor_c77ce72cb4764193) }

var fileDescriptor_c77ce72cb4764193 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x48, 0xd2, 0x2f,
	0x28, 0xca, 0x4f, 0x4e, 0x2d, 0x2e, 0x8e, 0xcf, 0x2f, 0x48, 0xcd, 0x8b, 0x4f, 0xcb, 0xcc, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0x2c, 0x56,
	0x72, 0xe7, 0xe2, 0x0f, 0x80, 0xa8, 0xf1, 0x2f, 0x48, 0xcd, 0x73, 0xcb, 0xcc, 0x49, 0x15, 0x12,
	0xe0, 0x62, 0x2e, 0xc8, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x02, 0x31, 0x85, 0xf8,
	0xb8, 0x98, 0xd2, 0x52, 0x24, 0x98, 0xc0, 0x02, 0x4c, 0x69, 0x29, 0x42, 0x42, 0x5c, 0x2c, 0x05,
	0x89, 0x25, 0x19, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x93, 0x51, 0x94, 0x41,
	0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x6e, 0x66, 0x72, 0x76, 0x6a,
	0x81, 0xb9, 0x99, 0x7e, 0x7e, 0x71, 0x61, 0x69, 0x6a, 0x51, 0xa5, 0x2e, 0xd8, 0xda, 0xa4, 0xd2,
	0x34, 0xfd, 0x82, 0xec, 0x74, 0x6b, 0xa8, 0xe5, 0x49, 0x6c, 0x60, 0x51, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xe1, 0xee, 0x29, 0x42, 0xaa, 0x00, 0x00, 0x00,
}
