// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/prometheus_metric.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Retrieve metrics from a Prometheus server.
type PrometheusMetric struct {
	// Address of prometheus target
	TargetName string `protobuf:"bytes,1,opt,name=target_name,json=targetName,proto3" json:"target_name"`
	// Name of collected Prometheus metric
	MetricName string `protobuf:"bytes,2,opt,name=metric_name,json=metricName,proto3" json:"metric_name"`
	// Value of collected Prometheus metric
	MetricValue float64 `protobuf:"fixed64,3,opt,name=metric_value,json=metricValue,proto3" json:"metric_value"`
	// Unix timestamp of collected data in MS
	TimestampMs          int64    `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrometheusMetric) Reset()         { *m = PrometheusMetric{} }
func (m *PrometheusMetric) String() string { return proto.CompactTextString(m) }
func (*PrometheusMetric) ProtoMessage()    {}
func (*PrometheusMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ad4c747780cac9a, []int{0}
}

func (m *PrometheusMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrometheusMetric.Unmarshal(m, b)
}
func (m *PrometheusMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrometheusMetric.Marshal(b, m, deterministic)
}
func (m *PrometheusMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrometheusMetric.Merge(m, src)
}
func (m *PrometheusMetric) XXX_Size() int {
	return xxx_messageInfo_PrometheusMetric.Size(m)
}
func (m *PrometheusMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_PrometheusMetric.DiscardUnknown(m)
}

var xxx_messageInfo_PrometheusMetric proto.InternalMessageInfo

func (m *PrometheusMetric) GetTargetName() string {
	if m != nil {
		return m.TargetName
	}
	return ""
}

func (m *PrometheusMetric) GetMetricName() string {
	if m != nil {
		return m.MetricName
	}
	return ""
}

func (m *PrometheusMetric) GetMetricValue() float64 {
	if m != nil {
		return m.MetricValue
	}
	return 0
}

func (m *PrometheusMetric) GetTimestampMs() int64 {
	if m != nil {
		return m.TimestampMs
	}
	return 0
}

func init() {
	proto.RegisterType((*PrometheusMetric)(nil), "schemas.PrometheusMetric")
}

func init() { proto.RegisterFile("pb/prometheus_metric.proto", fileDescriptor_3ad4c747780cac9a) }

var fileDescriptor_3ad4c747780cac9a = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xcf, 0xb1, 0x4a, 0xc7, 0x30,
	0x10, 0xc7, 0x71, 0x62, 0x45, 0x31, 0x75, 0x90, 0x4e, 0xc5, 0xc5, 0xea, 0xd4, 0xc5, 0x46, 0x14,
	0x74, 0x70, 0x73, 0xaf, 0x48, 0x07, 0x07, 0x97, 0x92, 0x84, 0xb3, 0x0d, 0xf5, 0x4c, 0x4c, 0x2e,
	0x82, 0xaf, 0xe2, 0xd3, 0xfe, 0x69, 0x52, 0xba, 0x7e, 0xf9, 0xdc, 0xc1, 0x8f, 0x5f, 0x3a, 0x25,
	0x9c, 0xb7, 0x08, 0x34, 0x43, 0x0c, 0x23, 0x02, 0x79, 0xa3, 0x3b, 0xe7, 0x2d, 0xd9, 0xea, 0x34,
	0xe8, 0x19, 0x50, 0x86, 0x9b, 0x7f, 0xc6, 0x2f, 0xde, 0x76, 0xd4, 0x27, 0x53, 0x5d, 0xf1, 0x92,
	0xa4, 0x9f, 0x80, 0xc6, 0x6f, 0x89, 0x50, 0xb3, 0x86, 0xb5, 0x67, 0x03, 0xcf, 0xe9, 0x55, 0x22,
	0xac, 0x20, 0xbf, 0xcb, 0xe0, 0x28, 0x83, 0x9c, 0x12, 0xb8, 0xe6, 0xe7, 0x1b, 0xf8, 0x95, 0x5f,
	0x11, 0xea, 0xa2, 0x61, 0x2d, 0x1b, 0xb6, 0xa3, 0xf7, 0x35, 0xad, 0x84, 0x0c, 0x42, 0x20, 0x89,
	0x6e, 0xc4, 0x50, 0x1f, 0x37, 0xac, 0x2d, 0x86, 0x72, 0x6f, 0x7d, 0x78, 0xb9, 0xff, 0xb8, 0x9b,
	0x0c, 0xcd, 0x51, 0x75, 0xda, 0xa2, 0x40, 0xa3, 0x17, 0x70, 0x4f, 0x8f, 0xc2, 0x86, 0x9f, 0x08,
	0xfe, 0xef, 0x36, 0x4d, 0x51, 0xf1, 0x53, 0xb8, 0x65, 0x7a, 0xde, 0x06, 0xa9, 0x93, 0x54, 0x1f,
	0x0e, 0x01, 0x00, 0x00, 0xff, 0xff, 0x79, 0x0b, 0xcf, 0x43, 0xfe, 0x00, 0x00, 0x00,
}
