// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/rpm_package_file.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// RPM packages that are currently installed on the host system.
type RpmPackageFile struct {
	// RPM package name
	Package string `protobuf:"bytes,1,opt,name=package,proto3" json:"package"`
	// File path within the package
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path"`
	// File default username from info DB
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username"`
	// File default groupname from info DB
	Groupname string `protobuf:"bytes,4,opt,name=groupname,proto3" json:"groupname"`
	// File permissions mode from info DB
	Mode string `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode"`
	// Expected file size in bytes from RPM info DB
	Size int64 `protobuf:"varint,6,opt,name=size,proto3" json:"size"`
	// SHA256 file digest from RPM info DB
	Sha256               string   `protobuf:"bytes,7,opt,name=sha256,proto3" json:"sha256"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpmPackageFile) Reset()         { *m = RpmPackageFile{} }
func (m *RpmPackageFile) String() string { return proto.CompactTextString(m) }
func (*RpmPackageFile) ProtoMessage()    {}
func (*RpmPackageFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_00602c9f4e616ab2, []int{0}
}

func (m *RpmPackageFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpmPackageFile.Unmarshal(m, b)
}
func (m *RpmPackageFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpmPackageFile.Marshal(b, m, deterministic)
}
func (m *RpmPackageFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpmPackageFile.Merge(m, src)
}
func (m *RpmPackageFile) XXX_Size() int {
	return xxx_messageInfo_RpmPackageFile.Size(m)
}
func (m *RpmPackageFile) XXX_DiscardUnknown() {
	xxx_messageInfo_RpmPackageFile.DiscardUnknown(m)
}

var xxx_messageInfo_RpmPackageFile proto.InternalMessageInfo

func (m *RpmPackageFile) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *RpmPackageFile) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RpmPackageFile) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RpmPackageFile) GetGroupname() string {
	if m != nil {
		return m.Groupname
	}
	return ""
}

func (m *RpmPackageFile) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *RpmPackageFile) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *RpmPackageFile) GetSha256() string {
	if m != nil {
		return m.Sha256
	}
	return ""
}

func init() {
	proto.RegisterType((*RpmPackageFile)(nil), "schemas.RpmPackageFile")
}

func init() { proto.RegisterFile("pb/rpm_package_file.proto", fileDescriptor_00602c9f4e616ab2) }

var fileDescriptor_00602c9f4e616ab2 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x15, 0x5a, 0x12, 0xea, 0x81, 0xc1, 0x03, 0x32, 0x88, 0xa1, 0x62, 0xea, 0x42, 0x8d,
	0x8a, 0x28, 0x03, 0x1b, 0x03, 0x33, 0xca, 0xc8, 0x52, 0xd9, 0xe6, 0x6a, 0x5b, 0xa9, 0xf1, 0x61,
	0xc7, 0x03, 0xfc, 0x32, 0x7e, 0x1e, 0xca, 0x25, 0xd0, 0xed, 0xbd, 0xef, 0xde, 0x3d, 0xe9, 0xb1,
	0x4b, 0xd4, 0x32, 0x61, 0xd8, 0xa1, 0x32, 0x9d, 0xb2, 0xb0, 0xdb, 0xfb, 0x03, 0xac, 0x31, 0xc5,
	0x3e, 0xf2, 0x26, 0x1b, 0x07, 0x41, 0xe5, 0x9b, 0x9f, 0x8a, 0x9d, 0xb7, 0x18, 0x5e, 0xc7, 0xc8,
	0x8b, 0x3f, 0x00, 0x17, 0xac, 0x99, 0x3e, 0x44, 0xb5, 0xac, 0x56, 0x8b, 0xf6, 0xcf, 0x72, 0xce,
	0xe6, 0xa8, 0x7a, 0x27, 0x4e, 0x08, 0x93, 0xe6, 0x57, 0xec, 0xac, 0x64, 0x48, 0x1f, 0x2a, 0x80,
	0x98, 0x11, 0xff, 0xf7, 0xfc, 0x9a, 0x2d, 0x6c, 0x8a, 0x05, 0xe9, 0x38, 0xa7, 0xe3, 0x11, 0x0c,
	0x6d, 0x21, 0xbe, 0x83, 0x38, 0x1d, 0xdb, 0x06, 0x3d, 0xb0, 0xec, 0xbf, 0x41, 0xd4, 0xcb, 0x6a,
	0x35, 0x6b, 0x49, 0xf3, 0x0b, 0x56, 0x67, 0xa7, 0x36, 0x0f, 0x5b, 0xd1, 0x50, 0x72, 0x72, 0xcf,
	0x9b, 0xb7, 0x3b, 0xeb, 0x7b, 0x57, 0xf4, 0xda, 0xc4, 0x20, 0x83, 0x37, 0x1d, 0xe0, 0xe3, 0x56,
	0xc6, 0xfc, 0x59, 0x20, 0x7d, 0xdd, 0xd2, 0x50, 0x5d, 0xf6, 0x12, 0x3b, 0xfb, 0x34, 0xcd, 0xd5,
	0x35, 0xd1, 0xfb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xab, 0xc8, 0xd3, 0x1b, 0x01, 0x00,
	0x00,
}
