// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/sandbox.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// OS X application sandboxes container details.
type Sandbox struct {
	// UTI-format bundle or label ID
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label"`
	// Sandbox owner
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user"`
	// Application sandboxings enabled on container
	Enabled int32 `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled"`
	// Sandbox-specific identifier
	BuildId string `protobuf:"bytes,4,opt,name=build_id,json=buildId,proto3" json:"build_id"`
	// Application bundle used by the sandbox
	BundlePath string `protobuf:"bytes,5,opt,name=bundle_path,json=bundlePath,proto3" json:"bundle_path"`
	// Path to sandbox container directory
	Path                 string   `protobuf:"bytes,6,opt,name=path,proto3" json:"path"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sandbox) Reset()         { *m = Sandbox{} }
func (m *Sandbox) String() string { return proto.CompactTextString(m) }
func (*Sandbox) ProtoMessage()    {}
func (*Sandbox) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce157d37d019a87, []int{0}
}

func (m *Sandbox) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sandbox.Unmarshal(m, b)
}
func (m *Sandbox) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sandbox.Marshal(b, m, deterministic)
}
func (m *Sandbox) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sandbox.Merge(m, src)
}
func (m *Sandbox) XXX_Size() int {
	return xxx_messageInfo_Sandbox.Size(m)
}
func (m *Sandbox) XXX_DiscardUnknown() {
	xxx_messageInfo_Sandbox.DiscardUnknown(m)
}

var xxx_messageInfo_Sandbox proto.InternalMessageInfo

func (m *Sandbox) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Sandbox) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Sandbox) GetEnabled() int32 {
	if m != nil {
		return m.Enabled
	}
	return 0
}

func (m *Sandbox) GetBuildId() string {
	if m != nil {
		return m.BuildId
	}
	return ""
}

func (m *Sandbox) GetBundlePath() string {
	if m != nil {
		return m.BundlePath
	}
	return ""
}

func (m *Sandbox) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*Sandbox)(nil), "schemas.Sandbox")
}

func init() { proto.RegisterFile("pb/sandbox.proto", fileDescriptor_fce157d37d019a87) }

var fileDescriptor_fce157d37d019a87 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x15, 0x68, 0x1a, 0x38, 0x16, 0x64, 0x31, 0x98, 0x89, 0x8a, 0xa9, 0x0b, 0x35, 0x02,
	0x09, 0x06, 0x36, 0x36, 0x36, 0x54, 0x36, 0x96, 0xca, 0x17, 0x1f, 0xb5, 0x55, 0x27, 0x36, 0xb1,
	0x2d, 0xc1, 0x8f, 0xe1, 0xbf, 0xa2, 0x9c, 0x61, 0xbb, 0xf7, 0x7d, 0x3a, 0x3d, 0x3d, 0x38, 0x8f,
	0xa8, 0x92, 0x1e, 0x0d, 0x86, 0xaf, 0x4d, 0x9c, 0x42, 0x0e, 0xa2, 0x4b, 0xbd, 0xa5, 0x41, 0xa7,
	0xeb, 0x9f, 0x06, 0xba, 0xb7, 0xaa, 0xc4, 0x05, 0xb4, 0x5e, 0x23, 0x79, 0xd9, 0xac, 0x9a, 0xf5,
	0xe9, 0xb6, 0x06, 0x21, 0x60, 0x51, 0x12, 0x4d, 0xf2, 0x88, 0x21, 0xdf, 0x42, 0x42, 0x47, 0xa3,
	0x46, 0x4f, 0x46, 0x1e, 0xaf, 0x9a, 0x75, 0xbb, 0xfd, 0x8f, 0xe2, 0x12, 0x4e, 0xb0, 0x38, 0x6f,
	0x76, 0xce, 0xc8, 0x05, 0x7f, 0x74, 0x9c, 0x5f, 0x8c, 0xb8, 0x82, 0x33, 0x2c, 0xa3, 0xf1, 0xb4,
	0x8b, 0x3a, 0x5b, 0xd9, 0xb2, 0x85, 0x8a, 0x5e, 0x75, 0xb6, 0x73, 0x13, 0x9b, 0x65, 0x6d, 0x9a,
	0xef, 0xe7, 0xbb, 0xf7, 0xdb, 0xbd, 0xcb, 0xb6, 0xe0, 0xa6, 0x0f, 0x83, 0x1a, 0x5c, 0x7f, 0xa0,
	0xf8, 0xf8, 0xa0, 0x42, 0xfa, 0x2c, 0x34, 0x7d, 0xdf, 0xf0, 0x1a, 0x2c, 0x1f, 0x2a, 0x1e, 0xf6,
	0x4f, 0x7f, 0x9b, 0x70, 0xc9, 0xf4, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0x91, 0xf8, 0xb4, 0xfc,
	0xf7, 0x00, 0x00, 0x00,
}
