// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/scheduled_task.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Lists all of the tasks in the Windows task scheduler.
type ScheduledTask struct {
	// Name of the scheduled task
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	// Actions executed by the scheduled task
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action"`
	// Path to the executable to be run
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path"`
	// Whether or not the scheduled task is enabled
	Enabled int32 `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled"`
	// State of the scheduled task
	State string `protobuf:"bytes,5,opt,name=state,proto3" json:"state"`
	// Whether or not the task is visible in the UI
	Hidden int32 `protobuf:"varint,6,opt,name=hidden,proto3" json:"hidden"`
	// Timestamp the task last ran
	LastRunTime int32 `protobuf:"varint,7,opt,name=last_run_time,json=lastRunTime,proto3" json:"last_run_time"`
	// Timestamp the task is scheduled to run next
	NextRunTime int32 `protobuf:"varint,8,opt,name=next_run_time,json=nextRunTime,proto3" json:"next_run_time"`
	// Exit status message of the last task run
	LastRunMessage string `protobuf:"bytes,9,opt,name=last_run_message,json=lastRunMessage,proto3" json:"last_run_message"`
	// Exit status code of the last task run
	LastRunCode          string   `protobuf:"bytes,10,opt,name=last_run_code,json=lastRunCode,proto3" json:"last_run_code"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScheduledTask) Reset()         { *m = ScheduledTask{} }
func (m *ScheduledTask) String() string { return proto.CompactTextString(m) }
func (*ScheduledTask) ProtoMessage()    {}
func (*ScheduledTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_4842cb41dfd7faf2, []int{0}
}

func (m *ScheduledTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduledTask.Unmarshal(m, b)
}
func (m *ScheduledTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduledTask.Marshal(b, m, deterministic)
}
func (m *ScheduledTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduledTask.Merge(m, src)
}
func (m *ScheduledTask) XXX_Size() int {
	return xxx_messageInfo_ScheduledTask.Size(m)
}
func (m *ScheduledTask) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduledTask.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduledTask proto.InternalMessageInfo

func (m *ScheduledTask) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScheduledTask) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ScheduledTask) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ScheduledTask) GetEnabled() int32 {
	if m != nil {
		return m.Enabled
	}
	return 0
}

func (m *ScheduledTask) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ScheduledTask) GetHidden() int32 {
	if m != nil {
		return m.Hidden
	}
	return 0
}

func (m *ScheduledTask) GetLastRunTime() int32 {
	if m != nil {
		return m.LastRunTime
	}
	return 0
}

func (m *ScheduledTask) GetNextRunTime() int32 {
	if m != nil {
		return m.NextRunTime
	}
	return 0
}

func (m *ScheduledTask) GetLastRunMessage() string {
	if m != nil {
		return m.LastRunMessage
	}
	return ""
}

func (m *ScheduledTask) GetLastRunCode() string {
	if m != nil {
		return m.LastRunCode
	}
	return ""
}

func init() {
	proto.RegisterType((*ScheduledTask)(nil), "schemas.ScheduledTask")
}

func init() { proto.RegisterFile("pb/scheduled_task.proto", fileDescriptor_4842cb41dfd7faf2) }

var fileDescriptor_4842cb41dfd7faf2 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4f, 0xb4, 0x30,
	0x10, 0x86, 0xc3, 0x7e, 0x0b, 0x7c, 0x5b, 0xb3, 0xc6, 0x34, 0x46, 0x7b, 0xdc, 0xec, 0x89, 0x8b,
	0x8b, 0xd1, 0x44, 0x0f, 0xde, 0xf4, 0xec, 0x05, 0xf7, 0xe4, 0x85, 0x0c, 0x74, 0x84, 0x06, 0xda,
	0x22, 0x6d, 0x13, 0xfd, 0x51, 0xfe, 0x47, 0xd3, 0x02, 0x46, 0x6f, 0xf3, 0x3e, 0x7d, 0xf2, 0x4e,
	0x33, 0xe4, 0x72, 0xa8, 0x72, 0x53, 0xb7, 0xc8, 0x5d, 0x8f, 0xbc, 0xb4, 0x60, 0xba, 0xc3, 0x30,
	0x6a, 0xab, 0x69, 0xea, 0xa9, 0x04, 0xb3, 0xff, 0x5a, 0x91, 0xed, 0xcb, 0x62, 0x1c, 0xc1, 0x74,
	0x94, 0x92, 0xb5, 0x02, 0x89, 0x2c, 0xda, 0x45, 0xd9, 0xa6, 0x08, 0x33, 0xbd, 0x20, 0x09, 0xd4,
	0x56, 0x68, 0xc5, 0x56, 0x81, 0xce, 0xc9, 0xbb, 0x03, 0xd8, 0x96, 0xfd, 0x9b, 0x5c, 0x3f, 0x53,
	0x46, 0x52, 0x54, 0x50, 0xf5, 0xc8, 0xd9, 0x7a, 0x17, 0x65, 0x71, 0xb1, 0x44, 0x7a, 0x4e, 0x62,
	0x63, 0xc1, 0x22, 0x8b, 0x83, 0x3e, 0x05, 0xdf, 0xdd, 0x0a, 0xce, 0x51, 0xb1, 0x24, 0xe8, 0x73,
	0xa2, 0x7b, 0xb2, 0xed, 0xc1, 0xd8, 0x72, 0x74, 0xaa, 0xb4, 0x42, 0x22, 0x4b, 0xc3, 0xf3, 0x89,
	0x87, 0x85, 0x53, 0x47, 0x21, 0xd1, 0x3b, 0x0a, 0x3f, 0x7e, 0x39, 0xff, 0x27, 0xc7, 0xc3, 0xc5,
	0xc9, 0xc8, 0xd9, 0x4f, 0x8f, 0x44, 0x63, 0xa0, 0x41, 0xb6, 0x09, 0x1f, 0x38, 0x9d, 0xab, 0x9e,
	0x27, 0xfa, 0x67, 0x63, 0xad, 0x39, 0x32, 0x12, 0xb4, 0x65, 0xe3, 0x93, 0xe6, 0xf8, 0x78, 0xf3,
	0x7a, 0xdd, 0x08, 0xdb, 0xba, 0xea, 0x50, 0x6b, 0x99, 0x4b, 0x51, 0x77, 0x38, 0xdc, 0xdf, 0xe5,
	0xda, 0xbc, 0x3b, 0x1c, 0x3f, 0xaf, 0xc2, 0x75, 0x2b, 0xf7, 0x96, 0x0f, 0x5d, 0xf3, 0x30, 0xdf,
	0xb8, 0x4a, 0x02, 0xbd, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x57, 0xc4, 0x62, 0x5a, 0x8e, 0x01,
	0x00, 0x00,
}
