// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/shared_resource.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Displays shared resources on a computer system running Windows. This may be a disk drive, printer, interprocess communication, or other sharable device.
type SharedResource struct {
	// A textual description of the object
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description"`
	// Indicates when the object was installed. Lack of a value does not indicate that the object is not installed.
	InstallDate string `protobuf:"bytes,2,opt,name=install_date,json=installDate,proto3" json:"install_date"`
	// String that indicates the current status of the object.
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status"`
	// Number of concurrent users for this resource has been limited. If True
	AllowMaximum int32 `protobuf:"varint,4,opt,name=allow_maximum,json=allowMaximum,proto3" json:"allow_maximum"`
	// Limit on the maximum number of users allowed to use this resource concurrently. The value is only valid if the AllowMaximum property is set to FALSE.
	MaximumAllowed int32 `protobuf:"varint,5,opt,name=maximum_allowed,json=maximumAllowed,proto3" json:"maximum_allowed"`
	// Alias given to a path set up as a share on a computer system running Windows.
	Name string `protobuf:"bytes,6,opt,name=name,proto3" json:"name"`
	// Local path of the Windows share.
	Path string `protobuf:"bytes,7,opt,name=path,proto3" json:"path"`
	// Type of resource being shared. Types include: disk drives
	Type                 int32    `protobuf:"varint,8,opt,name=type,proto3" json:"type"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharedResource) Reset()         { *m = SharedResource{} }
func (m *SharedResource) String() string { return proto.CompactTextString(m) }
func (*SharedResource) ProtoMessage()    {}
func (*SharedResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_112b82b8bc794ec5, []int{0}
}

func (m *SharedResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedResource.Unmarshal(m, b)
}
func (m *SharedResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedResource.Marshal(b, m, deterministic)
}
func (m *SharedResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedResource.Merge(m, src)
}
func (m *SharedResource) XXX_Size() int {
	return xxx_messageInfo_SharedResource.Size(m)
}
func (m *SharedResource) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedResource.DiscardUnknown(m)
}

var xxx_messageInfo_SharedResource proto.InternalMessageInfo

func (m *SharedResource) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SharedResource) GetInstallDate() string {
	if m != nil {
		return m.InstallDate
	}
	return ""
}

func (m *SharedResource) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SharedResource) GetAllowMaximum() int32 {
	if m != nil {
		return m.AllowMaximum
	}
	return 0
}

func (m *SharedResource) GetMaximumAllowed() int32 {
	if m != nil {
		return m.MaximumAllowed
	}
	return 0
}

func (m *SharedResource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SharedResource) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SharedResource) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func init() {
	proto.RegisterType((*SharedResource)(nil), "schemas.SharedResource")
}

func init() { proto.RegisterFile("pb/shared_resource.proto", fileDescriptor_112b82b8bc794ec5) }

var fileDescriptor_112b82b8bc794ec5 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd0, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x05, 0x60, 0x05, 0xda, 0x14, 0x4c, 0x29, 0x92, 0x07, 0xe4, 0x31, 0xc0, 0x40, 0x17, 0x1a,
	0x04, 0x12, 0x0c, 0x4c, 0x20, 0x56, 0x96, 0xb0, 0xb1, 0x44, 0x8e, 0x73, 0x34, 0x56, 0xe3, 0xd8,
	0xd8, 0x67, 0x41, 0x7f, 0x39, 0x2b, 0xca, 0xc5, 0x03, 0xdb, 0xf3, 0x77, 0x4f, 0x3e, 0xe9, 0x98,
	0x70, 0x4d, 0x19, 0x3a, 0xe9, 0xa1, 0xad, 0x3d, 0x04, 0x1b, 0xbd, 0x82, 0x8d, 0xf3, 0x16, 0x2d,
	0x5f, 0x04, 0xd5, 0x81, 0x91, 0xe1, 0xf2, 0x37, 0x63, 0xab, 0x77, 0xaa, 0x54, 0xa9, 0xc1, 0x0b,
	0x76, 0xd2, 0x42, 0x50, 0x5e, 0x3b, 0xd4, 0x76, 0x10, 0x59, 0x91, 0xad, 0x8f, 0xab, 0xff, 0xc4,
	0x2f, 0xd8, 0x52, 0x0f, 0x01, 0x65, 0xdf, 0xd7, 0xad, 0x44, 0x10, 0x07, 0x53, 0x25, 0xd9, 0xab,
	0x44, 0xe0, 0xe7, 0x2c, 0x0f, 0x28, 0x31, 0x06, 0x71, 0x48, 0xc3, 0xf4, 0xe2, 0x57, 0xec, 0x54,
	0xf6, 0xbd, 0xfd, 0xae, 0x8d, 0xfc, 0xd1, 0x26, 0x1a, 0x31, 0x2b, 0xb2, 0xf5, 0xbc, 0x5a, 0x12,
	0xbe, 0x4d, 0xc6, 0xaf, 0xd9, 0x59, 0x1a, 0xd7, 0xe4, 0xd0, 0x8a, 0x39, 0xd5, 0x56, 0x89, 0x9f,
	0x27, 0xe5, 0x9c, 0xcd, 0x06, 0x69, 0x40, 0xe4, 0xb4, 0x83, 0xf2, 0x68, 0x4e, 0x62, 0x27, 0x16,
	0x93, 0x8d, 0x79, 0x34, 0xdc, 0x3b, 0x10, 0x47, 0xf4, 0x0b, 0xe5, 0x97, 0xbb, 0x8f, 0xdb, 0xad,
	0xc6, 0x2e, 0x36, 0x1b, 0x65, 0x4d, 0x69, 0xb4, 0xda, 0x81, 0x7b, 0x7c, 0x28, 0x6d, 0xf8, 0x8a,
	0xe0, 0xf7, 0x37, 0x74, 0xa7, 0x26, 0x7e, 0x96, 0x6e, 0xb7, 0x7d, 0x4a, 0xd7, 0x6a, 0x72, 0xd2,
	0xfb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77, 0xaf, 0x32, 0x76, 0x59, 0x01, 0x00, 0x00,
}
