// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/sudoer.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Rules for running commands as other users via sudo.
type Sudoer struct {
	// Source file containing the given rule
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source"`
	// Symbol for given rule
	Header string `protobuf:"bytes,2,opt,name=header,proto3" json:"header"`
	// Rule definition
	RuleDetails          string   `protobuf:"bytes,3,opt,name=rule_details,json=ruleDetails,proto3" json:"rule_details"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sudoer) Reset()         { *m = Sudoer{} }
func (m *Sudoer) String() string { return proto.CompactTextString(m) }
func (*Sudoer) ProtoMessage()    {}
func (*Sudoer) Descriptor() ([]byte, []int) {
	return fileDescriptor_023244327bcaa482, []int{0}
}

func (m *Sudoer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sudoer.Unmarshal(m, b)
}
func (m *Sudoer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sudoer.Marshal(b, m, deterministic)
}
func (m *Sudoer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sudoer.Merge(m, src)
}
func (m *Sudoer) XXX_Size() int {
	return xxx_messageInfo_Sudoer.Size(m)
}
func (m *Sudoer) XXX_DiscardUnknown() {
	xxx_messageInfo_Sudoer.DiscardUnknown(m)
}

var xxx_messageInfo_Sudoer proto.InternalMessageInfo

func (m *Sudoer) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Sudoer) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *Sudoer) GetRuleDetails() string {
	if m != nil {
		return m.RuleDetails
	}
	return ""
}

func init() {
	proto.RegisterType((*Sudoer)(nil), "schemas.Sudoer")
}

func init() { proto.RegisterFile("pb/sudoer.proto", fileDescriptor_023244327bcaa482) }

var fileDescriptor_023244327bcaa482 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x48, 0xd2, 0x2f,
	0x2e, 0x4d, 0xc9, 0x4f, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0xce,
	0x48, 0xcd, 0x4d, 0x2c, 0x56, 0x8a, 0xe6, 0x62, 0x0b, 0x06, 0x4b, 0x08, 0x89, 0x71, 0xb1, 0x15,
	0xe7, 0x97, 0x16, 0x25, 0xa7, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x20, 0xf1,
	0x8c, 0xd4, 0xc4, 0x94, 0xd4, 0x22, 0x09, 0x26, 0x88, 0x38, 0x84, 0x27, 0xa4, 0xc8, 0xc5, 0x53,
	0x54, 0x9a, 0x93, 0x1a, 0x9f, 0x92, 0x5a, 0x92, 0x98, 0x99, 0x53, 0x2c, 0xc1, 0x0c, 0x96, 0xe5,
	0x06, 0x89, 0xb9, 0x40, 0x84, 0x9c, 0x8c, 0xa2, 0x0c, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4,
	0x92, 0xf3, 0x73, 0xf5, 0x73, 0x33, 0x93, 0xb3, 0x53, 0x0b, 0xcc, 0xcd, 0xf4, 0xf3, 0x8b, 0x0b,
	0x4b, 0x53, 0x8b, 0x2a, 0x75, 0xc1, 0x4e, 0x49, 0x2a, 0x4d, 0xd3, 0x2f, 0xc8, 0x4e, 0xb7, 0x86,
	0x3a, 0x28, 0x89, 0x0d, 0x2c, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x9f, 0xf4, 0x8e,
	0xb3, 0x00, 0x00, 0x00,
}
