// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/suid_bin.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// suid binaries in common locations.
type SuidBin struct {
	// Binary path
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path"`
	// Binary owner username
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username"`
	// Binary owner group
	Groupname string `protobuf:"bytes,3,opt,name=groupname,proto3" json:"groupname"`
	// Binary permissions
	Permissions          string   `protobuf:"bytes,4,opt,name=permissions,proto3" json:"permissions"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuidBin) Reset()         { *m = SuidBin{} }
func (m *SuidBin) String() string { return proto.CompactTextString(m) }
func (*SuidBin) ProtoMessage()    {}
func (*SuidBin) Descriptor() ([]byte, []int) {
	return fileDescriptor_9684229ca59e86ea, []int{0}
}

func (m *SuidBin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuidBin.Unmarshal(m, b)
}
func (m *SuidBin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuidBin.Marshal(b, m, deterministic)
}
func (m *SuidBin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuidBin.Merge(m, src)
}
func (m *SuidBin) XXX_Size() int {
	return xxx_messageInfo_SuidBin.Size(m)
}
func (m *SuidBin) XXX_DiscardUnknown() {
	xxx_messageInfo_SuidBin.DiscardUnknown(m)
}

var xxx_messageInfo_SuidBin proto.InternalMessageInfo

func (m *SuidBin) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SuidBin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SuidBin) GetGroupname() string {
	if m != nil {
		return m.Groupname
	}
	return ""
}

func (m *SuidBin) GetPermissions() string {
	if m != nil {
		return m.Permissions
	}
	return ""
}

func init() {
	proto.RegisterType((*SuidBin)(nil), "schemas.SuidBin")
}

func init() { proto.RegisterFile("pb/suid_bin.proto", fileDescriptor_9684229ca59e86ea) }

var fileDescriptor_9684229ca59e86ea = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xce, 0xbf, 0x0e, 0x82, 0x30,
	0x10, 0xc7, 0xf1, 0xa0, 0x44, 0xa4, 0x4e, 0x76, 0x22, 0xc6, 0x81, 0x38, 0xb9, 0x48, 0x8d, 0x26,
	0x3a, 0xb8, 0xf1, 0x08, 0xba, 0xb9, 0x18, 0x0a, 0x15, 0x2e, 0xa4, 0x7f, 0xec, 0xd1, 0x81, 0xb7,
	0x37, 0xb9, 0x18, 0x75, 0xbb, 0xfb, 0x7c, 0x97, 0x1f, 0x5b, 0x3a, 0x29, 0x30, 0x40, 0xf3, 0x90,
	0x60, 0x0a, 0xe7, 0xed, 0x60, 0x79, 0x82, 0x75, 0xa7, 0x74, 0x85, 0x9b, 0x91, 0x25, 0xb7, 0x00,
	0x4d, 0x09, 0x86, 0x73, 0x16, 0xbb, 0x6a, 0xe8, 0xb2, 0x28, 0x8f, 0xb6, 0xe9, 0x95, 0x6e, 0xbe,
	0x62, 0xf3, 0x80, 0xca, 0x9b, 0x4a, 0xab, 0x6c, 0x42, 0xfe, 0xfd, 0xf9, 0x9a, 0xa5, 0xad, 0xb7,
	0xc1, 0x51, 0x9c, 0x52, 0xfc, 0x01, 0xcf, 0xd9, 0xc2, 0x29, 0xaf, 0x01, 0x11, 0xac, 0xc1, 0x2c,
	0xa6, 0xfe, 0x4f, 0xe5, 0xe1, 0xbe, 0x6f, 0x61, 0xe8, 0x82, 0x2c, 0x6a, 0xab, 0x85, 0x86, 0xba,
	0x57, 0xee, 0x7c, 0x12, 0x16, 0x5f, 0x41, 0xf9, 0x71, 0x47, 0x43, 0x65, 0x78, 0x0a, 0xd7, 0xb7,
	0x97, 0xcf, 0x5c, 0x39, 0x23, 0x3d, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x88, 0x6b, 0x1d, 0x0c,
	0xd3, 0x00, 0x00, 0x00,
}
