// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/syslog_event.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type SyslogEvent struct {
	// Current unix epoch time
	Time int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time"`
	// Time known to syslog
	Datetime string `protobuf:"bytes,2,opt,name=datetime,proto3" json:"datetime"`
	// Hostname configured for syslog
	Host string `protobuf:"bytes,3,opt,name=host,proto3" json:"host"`
	// Syslog severity
	Severity int32 `protobuf:"varint,4,opt,name=severity,proto3" json:"severity"`
	// Syslog facility
	Facility string `protobuf:"bytes,5,opt,name=facility,proto3" json:"facility"`
	// The syslog tag
	Tag string `protobuf:"bytes,6,opt,name=tag,proto3" json:"tag"`
	// The syslog message
	Message string `protobuf:"bytes,7,opt,name=message,proto3" json:"message"`
	// Event ID
	Eid                  string   `protobuf:"bytes,8,opt,name=eid,proto3" json:"eid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyslogEvent) Reset()         { *m = SyslogEvent{} }
func (m *SyslogEvent) String() string { return proto.CompactTextString(m) }
func (*SyslogEvent) ProtoMessage()    {}
func (*SyslogEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcf1e54a6979b83f, []int{0}
}

func (m *SyslogEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyslogEvent.Unmarshal(m, b)
}
func (m *SyslogEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyslogEvent.Marshal(b, m, deterministic)
}
func (m *SyslogEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyslogEvent.Merge(m, src)
}
func (m *SyslogEvent) XXX_Size() int {
	return xxx_messageInfo_SyslogEvent.Size(m)
}
func (m *SyslogEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SyslogEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SyslogEvent proto.InternalMessageInfo

func (m *SyslogEvent) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *SyslogEvent) GetDatetime() string {
	if m != nil {
		return m.Datetime
	}
	return ""
}

func (m *SyslogEvent) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *SyslogEvent) GetSeverity() int32 {
	if m != nil {
		return m.Severity
	}
	return 0
}

func (m *SyslogEvent) GetFacility() string {
	if m != nil {
		return m.Facility
	}
	return ""
}

func (m *SyslogEvent) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *SyslogEvent) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SyslogEvent) GetEid() string {
	if m != nil {
		return m.Eid
	}
	return ""
}

func init() {
	proto.RegisterType((*SyslogEvent)(nil), "schemas.SyslogEvent")
}

func init() { proto.RegisterFile("pb/syslog_event.proto", fileDescriptor_dcf1e54a6979b83f) }

var fileDescriptor_dcf1e54a6979b83f = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x59, 0xd3, 0x36, 0x75, 0xbd, 0xc8, 0x82, 0xb0, 0x78, 0x0a, 0x9e, 0x72, 0xb1, 0x11,
	0x05, 0x3d, 0x78, 0x13, 0x7c, 0x81, 0x78, 0xf3, 0x22, 0x9b, 0xcd, 0x74, 0xb3, 0xb4, 0xeb, 0xae,
	0x99, 0x49, 0x21, 0x4f, 0xe8, 0x6b, 0xc9, 0x4e, 0x6d, 0x6f, 0xff, 0xff, 0xfd, 0x1f, 0x03, 0x23,
	0x6f, 0x52, 0xd7, 0xe0, 0x8c, 0xfb, 0xe8, 0xbe, 0xe0, 0x00, 0xdf, 0xb4, 0x49, 0x63, 0xa4, 0xa8,
	0x4a, 0xb4, 0x03, 0x04, 0x83, 0x77, 0xbf, 0x42, 0x5e, 0x7d, 0xf0, 0xfe, 0x9e, 0x67, 0xa5, 0xe4,
	0x82, 0x7c, 0x00, 0x2d, 0x2a, 0x51, 0x17, 0x2d, 0x67, 0x75, 0x2b, 0xd7, 0xbd, 0x21, 0x60, 0x7e,
	0x51, 0x89, 0xfa, 0xb2, 0x3d, 0xf7, 0xec, 0x0f, 0x11, 0x49, 0x17, 0xcc, 0x39, 0x67, 0x1f, 0xe1,
	0x00, 0xa3, 0xa7, 0x59, 0x2f, 0x2a, 0x51, 0x2f, 0xdb, 0x73, 0xcf, 0xdb, 0xd6, 0x58, 0xbf, 0xcf,
	0xdb, 0xf2, 0x78, 0xeb, 0xd4, 0xd5, 0xb5, 0x2c, 0xc8, 0x38, 0xbd, 0x62, 0x9c, 0xa3, 0xd2, 0xb2,
	0x0c, 0x80, 0x68, 0x1c, 0xe8, 0x92, 0xe9, 0xa9, 0x66, 0x17, 0x7c, 0xaf, 0xd7, 0x47, 0x17, 0x7c,
	0xff, 0xf6, 0xf8, 0xf9, 0xe0, 0x3c, 0x0d, 0x53, 0xb7, 0xb1, 0x31, 0x34, 0xc1, 0xdb, 0x1d, 0xa4,
	0x97, 0xe7, 0x26, 0xe2, 0xcf, 0x04, 0xe3, 0x7c, 0xcf, 0x7f, 0x77, 0xd3, 0xb6, 0x49, 0x3b, 0xf7,
	0xfa, 0xff, 0x7d, 0xb7, 0x62, 0xfa, 0xf4, 0x17, 0x00, 0x00, 0xff, 0xff, 0x22, 0xf1, 0x7b, 0x1a,
	0x26, 0x01, 0x00, 0x00,
}
