// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/system_control.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// sysctl names, values, and settings information.
type SystemControl struct {
	// Full sysctl MIB name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	// Control MIB
	Oid string `protobuf:"bytes,2,opt,name=oid,proto3" json:"oid"`
	// Subsystem ID
	Subsystem string `protobuf:"bytes,3,opt,name=subsystem,proto3" json:"subsystem"`
	// Value of setting
	CurrentValue string `protobuf:"bytes,4,opt,name=current_value,json=currentValue,proto3" json:"current_value"`
	// The MIB value set in /etc/sysctl.conf
	ConfigValue string `protobuf:"bytes,5,opt,name=config_value,json=configValue,proto3" json:"config_value"`
	// Data type
	Type string `protobuf:"bytes,6,opt,name=type,proto3" json:"type"`
	// Specific attribute of opaque type
	FieldName            string   `protobuf:"bytes,7,opt,name=field_name,json=fieldName,proto3" json:"field_name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemControl) Reset()         { *m = SystemControl{} }
func (m *SystemControl) String() string { return proto.CompactTextString(m) }
func (*SystemControl) ProtoMessage()    {}
func (*SystemControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_f74d0948aefa538e, []int{0}
}

func (m *SystemControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemControl.Unmarshal(m, b)
}
func (m *SystemControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemControl.Marshal(b, m, deterministic)
}
func (m *SystemControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemControl.Merge(m, src)
}
func (m *SystemControl) XXX_Size() int {
	return xxx_messageInfo_SystemControl.Size(m)
}
func (m *SystemControl) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemControl.DiscardUnknown(m)
}

var xxx_messageInfo_SystemControl proto.InternalMessageInfo

func (m *SystemControl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SystemControl) GetOid() string {
	if m != nil {
		return m.Oid
	}
	return ""
}

func (m *SystemControl) GetSubsystem() string {
	if m != nil {
		return m.Subsystem
	}
	return ""
}

func (m *SystemControl) GetCurrentValue() string {
	if m != nil {
		return m.CurrentValue
	}
	return ""
}

func (m *SystemControl) GetConfigValue() string {
	if m != nil {
		return m.ConfigValue
	}
	return ""
}

func (m *SystemControl) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SystemControl) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func init() {
	proto.RegisterType((*SystemControl)(nil), "schemas.SystemControl")
}

func init() { proto.RegisterFile("pb/system_control.proto", fileDescriptor_f74d0948aefa538e) }

var fileDescriptor_f74d0948aefa538e = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x3d, 0x4b, 0xc4, 0x40,
	0x10, 0x86, 0x89, 0x17, 0xef, 0xb8, 0xf1, 0x0e, 0x64, 0x1a, 0x53, 0x28, 0xf8, 0xd1, 0xd8, 0x78,
	0x11, 0x05, 0x2d, 0xec, 0xb4, 0xb7, 0x50, 0xb0, 0xb0, 0x09, 0xd9, 0xbd, 0x49, 0x6e, 0xb9, 0x6c,
	0x76, 0xdd, 0x0f, 0x21, 0x7f, 0xd2, 0xdf, 0x24, 0x99, 0x0d, 0x5c, 0xf7, 0xf2, 0xf0, 0x30, 0xf3,
	0xce, 0xc0, 0x99, 0x15, 0xa5, 0x1f, 0x7c, 0x20, 0x5d, 0x49, 0xd3, 0x07, 0x67, 0xba, 0x8d, 0x75,
	0x26, 0x18, 0x5c, 0x78, 0xb9, 0x23, 0x5d, 0xfb, 0xeb, 0xbf, 0x0c, 0xd6, 0x9f, 0x6c, 0xbc, 0x25,
	0x01, 0x11, 0xf2, 0xbe, 0xd6, 0x54, 0x64, 0x97, 0xd9, 0xed, 0xf2, 0x83, 0x33, 0x9e, 0xc2, 0xcc,
	0xa8, 0x6d, 0x71, 0xc4, 0x68, 0x8c, 0x78, 0x0e, 0x4b, 0x1f, 0x45, 0x9a, 0x5d, 0xcc, 0x98, 0x1f,
	0x00, 0xde, 0xc0, 0x5a, 0x46, 0xe7, 0xa8, 0x0f, 0xd5, 0x6f, 0xdd, 0x45, 0x2a, 0x72, 0x36, 0x56,
	0x13, 0xfc, 0x1a, 0x19, 0x5e, 0xc1, 0x4a, 0x9a, 0xbe, 0x51, 0xed, 0xe4, 0x1c, 0xb3, 0x73, 0x92,
	0x58, 0x52, 0x10, 0xf2, 0x30, 0x58, 0x2a, 0xe6, 0xa9, 0xcb, 0x98, 0xf1, 0x02, 0xa0, 0x51, 0xd4,
	0x6d, 0x2b, 0x6e, 0xb9, 0x48, 0xab, 0x99, 0xbc, 0xd7, 0x9a, 0x5e, 0x1f, 0xbe, 0xef, 0x5b, 0x15,
	0x76, 0x51, 0x6c, 0xa4, 0xd1, 0xa5, 0x56, 0x72, 0x4f, 0xf6, 0xf9, 0xa9, 0x34, 0xfe, 0x27, 0x92,
	0x1b, 0xee, 0xf8, 0x7c, 0x11, 0x9b, 0xd2, 0xee, 0xdb, 0x97, 0xe9, 0x09, 0x62, 0xce, 0xf4, 0xf1,
	0x3f, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xaf, 0xd1, 0x8c, 0x2f, 0x01, 0x00, 0x00,
}
