// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/temperature_sensor.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Machine's temperature sensors.
type TemperatureSensor struct {
	// The SMC key on OS X
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	// Name of temperature source
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	// Temperature in Celsius
	Celsius float64 `protobuf:"fixed64,3,opt,name=celsius,proto3" json:"celsius"`
	// Temperature in Fahrenheit
	Fahrenheit           float64  `protobuf:"fixed64,4,opt,name=fahrenheit,proto3" json:"fahrenheit"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemperatureSensor) Reset()         { *m = TemperatureSensor{} }
func (m *TemperatureSensor) String() string { return proto.CompactTextString(m) }
func (*TemperatureSensor) ProtoMessage()    {}
func (*TemperatureSensor) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e149a8305113f9a, []int{0}
}

func (m *TemperatureSensor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemperatureSensor.Unmarshal(m, b)
}
func (m *TemperatureSensor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemperatureSensor.Marshal(b, m, deterministic)
}
func (m *TemperatureSensor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemperatureSensor.Merge(m, src)
}
func (m *TemperatureSensor) XXX_Size() int {
	return xxx_messageInfo_TemperatureSensor.Size(m)
}
func (m *TemperatureSensor) XXX_DiscardUnknown() {
	xxx_messageInfo_TemperatureSensor.DiscardUnknown(m)
}

var xxx_messageInfo_TemperatureSensor proto.InternalMessageInfo

func (m *TemperatureSensor) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TemperatureSensor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TemperatureSensor) GetCelsius() float64 {
	if m != nil {
		return m.Celsius
	}
	return 0
}

func (m *TemperatureSensor) GetFahrenheit() float64 {
	if m != nil {
		return m.Fahrenheit
	}
	return 0
}

func init() {
	proto.RegisterType((*TemperatureSensor)(nil), "schemas.TemperatureSensor")
}

func init() { proto.RegisterFile("pb/temperature_sensor.proto", fileDescriptor_3e149a8305113f9a) }

var fileDescriptor_3e149a8305113f9a = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x31, 0x6b, 0xc3, 0x30,
	0x10, 0x46, 0x51, 0x6d, 0x6a, 0xaa, 0xa9, 0xd5, 0x24, 0x28, 0x14, 0xd3, 0xc9, 0x4b, 0xad, 0xd2,
	0x42, 0x3b, 0x74, 0xeb, 0x4f, 0x70, 0x32, 0x65, 0x09, 0x92, 0x38, 0x5b, 0xc2, 0x91, 0xa5, 0xe8,
	0xa4, 0xc1, 0xff, 0x3e, 0x44, 0x24, 0x24, 0xdb, 0x77, 0xef, 0xde, 0xf0, 0xe8, 0x6b, 0x50, 0x22,
	0x81, 0x0b, 0x10, 0x65, 0xca, 0x11, 0xf6, 0x08, 0x0b, 0xfa, 0xd8, 0x87, 0xe8, 0x93, 0x67, 0x0d,
	0x6a, 0x03, 0x4e, 0xe2, 0x3b, 0xd2, 0x97, 0xed, 0x4d, 0xda, 0x14, 0x87, 0x3d, 0xd3, 0x6a, 0x86,
	0x95, 0x93, 0x96, 0x74, 0x4f, 0xc3, 0x79, 0x32, 0x46, 0xeb, 0x45, 0x3a, 0xe0, 0x0f, 0x05, 0x95,
	0xcd, 0x38, 0x6d, 0x34, 0x1c, 0xd0, 0x66, 0xe4, 0x55, 0x4b, 0x3a, 0x32, 0x5c, 0x4f, 0xf6, 0x46,
	0xe9, 0x28, 0x4d, 0x84, 0xc5, 0x80, 0x4d, 0xbc, 0x2e, 0xcf, 0x3b, 0xf2, 0xff, 0xb5, 0xfb, 0x9c,
	0x6c, 0x32, 0x59, 0xf5, 0xda, 0x3b, 0xe1, 0xac, 0x9e, 0x21, 0xfc, 0xfe, 0x08, 0x8f, 0xc7, 0x0c,
	0x71, 0xfd, 0x28, 0x89, 0x2a, 0x8f, 0x22, 0xcc, 0xd3, 0xdf, 0x25, 0x54, 0x3d, 0x16, 0xfa, 0x7d,
	0x0a, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xa4, 0xa2, 0x1e, 0xd7, 0x00, 0x00, 0x00,
}
