// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/uptime.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Track time passed since last boot.
type Uptime struct {
	// Days of uptime
	Days int32 `protobuf:"varint,1,opt,name=days,proto3" json:"days"`
	// Hours of uptime
	Hours int32 `protobuf:"varint,2,opt,name=hours,proto3" json:"hours"`
	// Minutes of uptime
	Minutes int32 `protobuf:"varint,3,opt,name=minutes,proto3" json:"minutes"`
	// Seconds of uptime
	Seconds int32 `protobuf:"varint,4,opt,name=seconds,proto3" json:"seconds"`
	// Total uptime seconds
	TotalSeconds         int64    `protobuf:"varint,5,opt,name=total_seconds,json=totalSeconds,proto3" json:"total_seconds"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Uptime) Reset()         { *m = Uptime{} }
func (m *Uptime) String() string { return proto.CompactTextString(m) }
func (*Uptime) ProtoMessage()    {}
func (*Uptime) Descriptor() ([]byte, []int) {
	return fileDescriptor_f715de91d3c42d31, []int{0}
}

func (m *Uptime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Uptime.Unmarshal(m, b)
}
func (m *Uptime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Uptime.Marshal(b, m, deterministic)
}
func (m *Uptime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uptime.Merge(m, src)
}
func (m *Uptime) XXX_Size() int {
	return xxx_messageInfo_Uptime.Size(m)
}
func (m *Uptime) XXX_DiscardUnknown() {
	xxx_messageInfo_Uptime.DiscardUnknown(m)
}

var xxx_messageInfo_Uptime proto.InternalMessageInfo

func (m *Uptime) GetDays() int32 {
	if m != nil {
		return m.Days
	}
	return 0
}

func (m *Uptime) GetHours() int32 {
	if m != nil {
		return m.Hours
	}
	return 0
}

func (m *Uptime) GetMinutes() int32 {
	if m != nil {
		return m.Minutes
	}
	return 0
}

func (m *Uptime) GetSeconds() int32 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Uptime) GetTotalSeconds() int64 {
	if m != nil {
		return m.TotalSeconds
	}
	return 0
}

func init() {
	proto.RegisterType((*Uptime)(nil), "schemas.Uptime")
}

func init() { proto.RegisterFile("pb/uptime.proto", fileDescriptor_f715de91d3c42d31) }

var fileDescriptor_f715de91d3c42d31 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x48, 0xd2, 0x2f,
	0x2d, 0x28, 0xc9, 0xcc, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0xce,
	0x48, 0xcd, 0x4d, 0x2c, 0x56, 0xea, 0x66, 0xe4, 0x62, 0x0b, 0x05, 0xcb, 0x08, 0x09, 0x71, 0xb1,
	0xa4, 0x24, 0x56, 0x16, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c,
	0xac, 0x19, 0xf9, 0xa5, 0x45, 0xc5, 0x12, 0x4c, 0x60, 0x41, 0x08, 0x47, 0x48, 0x82, 0x8b, 0x3d,
	0x37, 0x33, 0xaf, 0xb4, 0x24, 0xb5, 0x58, 0x82, 0x19, 0x2c, 0x0e, 0xe3, 0x82, 0x64, 0x8a, 0x53,
	0x93, 0xf3, 0xf3, 0x52, 0x8a, 0x25, 0x58, 0x20, 0x32, 0x50, 0xae, 0x90, 0x32, 0x17, 0x6f, 0x49,
	0x7e, 0x49, 0x62, 0x4e, 0x3c, 0x4c, 0x9e, 0x55, 0x81, 0x51, 0x83, 0x39, 0x88, 0x07, 0x2c, 0x18,
	0x0c, 0x11, 0x73, 0x32, 0x8a, 0x32, 0x48, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf,
	0xd5, 0xcf, 0xcd, 0x4c, 0xce, 0x4e, 0x2d, 0x30, 0x37, 0xd3, 0xcf, 0x2f, 0x2e, 0x2c, 0x4d, 0x2d,
	0xaa, 0xd4, 0x05, 0xbb, 0x3d, 0xa9, 0x34, 0x4d, 0xbf, 0x20, 0x3b, 0xdd, 0x1a, 0xea, 0x83, 0x24,
	0x36, 0xb0, 0xa8, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x43, 0x2c, 0xdd, 0x9b, 0xe4, 0x00, 0x00,
	0x00,
}
