// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/user.proto

package schemas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Local user accounts (including domain accounts that have logged on locally (Windows)).
type User struct {
	// User ID
	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid"`
	// Group ID (unsigned)
	Gid int64 `protobuf:"varint,2,opt,name=gid,proto3" json:"gid"`
	// User ID as int64 signed (Apple)
	UidSigned int64 `protobuf:"varint,3,opt,name=uid_signed,json=uidSigned,proto3" json:"uid_signed"`
	// Default group ID as int64 signed (Apple)
	GidSigned int64 `protobuf:"varint,4,opt,name=gid_signed,json=gidSigned,proto3" json:"gid_signed"`
	// Username
	Username string `protobuf:"bytes,5,opt,name=username,proto3" json:"username"`
	// Optional user description
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description"`
	// User's home directory
	Directory string `protobuf:"bytes,7,opt,name=directory,proto3" json:"directory"`
	// User's configured default shell
	Shell string `protobuf:"bytes,8,opt,name=shell,proto3" json:"shell"`
	// User's UUID (Apple) or SID (Windows)
	Uuid string `protobuf:"bytes,9,opt,name=uuid,proto3" json:"uuid"`
	// Whether the account is roaming (domain)
	Type string `protobuf:"bytes,10,opt,name=type,proto3" json:"type"`
	// IsHidden attribute set in OpenDirectory
	IsHidden             int32    `protobuf:"varint,11,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *User) GetGid() int64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *User) GetUidSigned() int64 {
	if m != nil {
		return m.UidSigned
	}
	return 0
}

func (m *User) GetGidSigned() int64 {
	if m != nil {
		return m.GidSigned
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

func (m *User) GetShell() string {
	if m != nil {
		return m.Shell
	}
	return ""
}

func (m *User) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *User) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *User) GetIsHidden() int32 {
	if m != nil {
		return m.IsHidden
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "schemas.User")
}

func init() { proto.RegisterFile("pb/user.proto", fileDescriptor_c4f917211a932270) }

var fileDescriptor_c4f917211a932270 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x95, 0x26, 0x69, 0x93, 0xab, 0x90, 0x90, 0xc5, 0x60, 0xf1, 0x47, 0x8a, 0x98, 0xb2,
	0xd0, 0x20, 0x90, 0x60, 0x60, 0x63, 0x62, 0x0e, 0x62, 0x61, 0xa9, 0x9a, 0xf8, 0x70, 0x4e, 0x6d,
	0x62, 0x63, 0xc7, 0x43, 0x3e, 0x0d, 0x5f, 0x15, 0xd9, 0x41, 0x2d, 0xdb, 0x7b, 0xbf, 0xdf, 0x72,
	0xf7, 0xe0, 0x4c, 0x37, 0x95, 0xb3, 0x68, 0x36, 0xda, 0xa8, 0x51, 0xb1, 0x95, 0x6d, 0x3b, 0xec,
	0x77, 0xf6, 0xf6, 0x67, 0x01, 0xc9, 0x87, 0x45, 0xc3, 0xce, 0x21, 0x76, 0x24, 0x78, 0x54, 0x44,
	0x65, 0x5c, 0xfb, 0xe8, 0x89, 0x24, 0xc1, 0x17, 0x33, 0x91, 0x24, 0xd8, 0x0d, 0x80, 0x23, 0xb1,
	0xb5, 0x24, 0x07, 0x14, 0x3c, 0x0e, 0x22, 0x77, 0x24, 0xde, 0x03, 0xf0, 0x5a, 0x9e, 0x74, 0x32,
	0x6b, 0x79, 0xd4, 0x97, 0x90, 0xf9, 0x0b, 0x86, 0x5d, 0x8f, 0x3c, 0x2d, 0xa2, 0x32, 0xaf, 0x8f,
	0x9d, 0x15, 0xb0, 0x16, 0x68, 0x5b, 0x43, 0x7a, 0x24, 0x35, 0xf0, 0x65, 0xd0, 0xff, 0x11, 0xbb,
	0x86, 0x5c, 0x90, 0xc1, 0x76, 0x54, 0x66, 0xe2, 0xab, 0xe0, 0x4f, 0x80, 0x5d, 0x40, 0x6a, 0x3b,
	0x3c, 0x1c, 0x78, 0x16, 0xcc, 0x5c, 0x18, 0x83, 0xc4, 0xf9, 0xa7, 0xf2, 0x00, 0x43, 0xf6, 0x6c,
	0x9c, 0x34, 0x72, 0x98, 0x99, 0xcf, 0xec, 0x0a, 0x72, 0xb2, 0xdb, 0x8e, 0x84, 0xc0, 0x81, 0xaf,
	0x8b, 0xa8, 0x4c, 0xeb, 0x8c, 0xec, 0x5b, 0xe8, 0xaf, 0x0f, 0x9f, 0xf7, 0x92, 0xc6, 0xce, 0x35,
	0x9b, 0x56, 0xf5, 0x55, 0x4f, 0xed, 0x1e, 0xf5, 0xf3, 0x53, 0xa5, 0xec, 0xb7, 0x43, 0x33, 0xdd,
	0x85, 0x3d, 0x1b, 0xf7, 0x55, 0xe9, 0xbd, 0x7c, 0xf9, 0x5b, 0xb5, 0x59, 0x06, 0xfa, 0xf8, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0x73, 0x7f, 0xae, 0x1d, 0x76, 0x01, 0x00, 0x00,
}
